#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQAdditionalRecipient
@end

@interface SQAdditionalRecipient : SQObject

/* The location ID for a recipient (other than the merchant) receiving a portion of this tender. 
 */
@property(nonatomic) NSString* locationId;
/* The description of the additional recipient. [optional]
 */
@property(nonatomic) NSString* _description;
/* The amount of money distributed to the recipient. 
 */
@property(nonatomic) SQMoney* amountMoney;
/* The unique ID for the RETIRED `AdditionalRecipientReceivable` object. This field should be empty for any `AdditionalRecipient` objects created after the retirement. [optional]
 */
@property(nonatomic) NSString* receivableId;

@end
