#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQApplicationDetails
@end

@interface SQApplicationDetails : SQObject

/* The Square product, such as Square Point of Sale (POS),  Square Invoices, or Square Virtual Terminal. [optional]
 */
@property(nonatomic) NSString* squareProduct;
/* The Square ID assigned to the application used to take the payment.  Application developers can use this information to identify payments that  their application processed.  For example, if a developer uses a custom application to process payments,  this field contains the application ID from the Developer Dashboard.  If a seller uses a [Square App Marketplace](https://developer.squareup.com/docs/app-marketplace)  application to process payments, the field contains the corresponding application ID. [optional]
 */
@property(nonatomic) NSString* applicationId;

@end
