#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBatchRetrieveCatalogObjectsRequest
@end

@interface SQBatchRetrieveCatalogObjectsRequest : SQObject

/* The IDs of the CatalogObjects to be retrieved. 
 */
@property(nonatomic) NSArray<NSString*>* objectIds;
/* If `true`, the response will include additional objects that are related to the requested objects. Related objects are defined as any objects referenced by ID by the results in the `objects` field of the response. These objects are put in the `related_objects` field. Setting this to `true` is helpful when the objects are needed for immediate display to a user. This process only goes one level deep. Objects referenced by the related objects will not be included. For example,  if the `objects` field of the response contains a CatalogItem, its associated CatalogCategory objects, CatalogTax objects, CatalogImage objects and CatalogModifierLists will be returned in the `related_objects` field of the response. If the `objects` field of the response contains a CatalogItemVariation, its parent CatalogItem will be returned in the `related_objects` field of the response.  Default value: `false` [optional]
 */
@property(nonatomic) NSNumber* includeRelatedObjects;
/* The specific version of the catalog objects to be included in the response.  This allows you to retrieve historical versions of objects. The specified version value is matched against the [CatalogObject](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogObject)s' `version` attribute. If not included, results will be from the current version of the catalog. [optional]
 */
@property(nonatomic) NSNumber* catalogVersion;
/* Indicates whether to include (`true`) or not (`false`) in the response deleted objects, namely, those with the `is_deleted` attribute set to `true`. [optional]
 */
@property(nonatomic) NSNumber* includeDeletedObjects;

@end
