#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBatchRetrieveInventoryChangesRequest
@end

@interface SQBatchRetrieveInventoryChangesRequest : SQObject

/* The filter to return results by `CatalogObject` ID. The filter is only applicable when set. The default value is null. [optional]
 */
@property(nonatomic) NSArray<NSString*>* catalogObjectIds;
/* The filter to return results by `Location` ID. The filter is only applicable when set. The default value is null. [optional]
 */
@property(nonatomic) NSArray<NSString*>* locationIds;
/* The filter to return results by `InventoryChangeType` values other than `TRANSFER`. The default value is `[PHYSICAL_COUNT, ADJUSTMENT]`. [optional]
 */
@property(nonatomic) NSArray<NSString*>* types;
/* The filter to return `ADJUSTMENT` query results by `InventoryState`. This filter is only applied when set. The default value is null. [optional]
 */
@property(nonatomic) NSArray<NSString*>* states;
/* The filter to return results with their `calculated_at` value after the given time as specified in an RFC 3339 timestamp. The default value is the UNIX epoch of (`1970-01-01T00:00:00Z`). [optional]
 */
@property(nonatomic) NSString* updatedAfter;
/* The filter to return results with their `created_at` or `calculated_at` value strictly before the given time as specified in an RFC 3339 timestamp. The default value is the UNIX epoch of (`1970-01-01T00:00:00Z`). [optional]
 */
@property(nonatomic) NSString* updatedBefore;
/* A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for the original query.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information. [optional]
 */
@property(nonatomic) NSString* cursor;
/* The number of [records](https://developer.squareup.com/reference/square_2023-10-18/objects/InventoryChange) to return. [optional]
 */
@property(nonatomic) NSNumber* limit;

@end
