#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBatchRetrieveOrdersRequest
@end

@interface SQBatchRetrieveOrdersRequest : SQObject

/* The ID of the location for these orders. This field is optional: omit it to retrieve orders within the scope of the current authorization's merchant ID. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The IDs of the orders to retrieve. A maximum of 100 orders can be retrieved per request. 
 */
@property(nonatomic) NSArray<NSString*>* orderIds;

@end
