#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCatalogIdMapping.h"
#import "SQCatalogObject.h"
#import "SQError.h"
@protocol SQCatalogIdMapping;
@class SQCatalogIdMapping;
@protocol SQCatalogObject;
@class SQCatalogObject;
@protocol SQError;
@class SQError;



@protocol SQBatchUpsertCatalogObjectsResponse
@end

@interface SQBatchUpsertCatalogObjectsResponse : SQObject

/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The created successfully created CatalogObjects. [optional]
 */
@property(nonatomic) NSArray<SQCatalogObject>* objects;
/* The database [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) of this update in RFC 3339 format, e.g., \"2016-09-04T23:59:33.123Z\". [optional]
 */
@property(nonatomic) NSString* updatedAt;
/* The mapping between client and server IDs for this upsert. [optional]
 */
@property(nonatomic) NSArray<SQCatalogIdMapping>* idMappings;

@end
