#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
@protocol SQError;
@class SQError;



@protocol SQBookingCustomAttributeDeleteResponse
@end

@interface SQBookingCustomAttributeDeleteResponse : SQObject

/* The ID of the [booking](https://developer.squareup.com/reference/square_2023-10-18/objects/Booking) associated with the custom attribute. [optional]
 */
@property(nonatomic) NSString* bookingId;
/* Any errors that occurred while processing the individual request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
