#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBookingCreatorDetails
@end

@interface SQBookingCreatorDetails : SQObject

/* The seller-accessible type of the creator of the booking. [optional]
 */
@property(nonatomic) NSString* creatorType;
/* The ID of the team member who created the booking, when the booking creator is of the `TEAM_MEMBER` type. Access to this field requires seller-level permissions. [optional]
 */
@property(nonatomic) NSString* teamMemberId;
/* The ID of the customer who created the booking, when the booking creator is of the `CUSTOMER` type. Access to this field requires seller-level permissions. [optional]
 */
@property(nonatomic) NSString* customerId;

@end
