#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCreateVendorResponse.h"
#import "SQError.h"
@protocol SQCreateVendorResponse;
@class SQCreateVendorResponse;
@protocol SQError;
@class SQError;



@protocol SQBulkCreateVendorsResponse
@end

@interface SQBulkCreateVendorsResponse : SQObject

/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* A set of [CreateVendorResponse](https://developer.squareup.com/reference/square_2023-10-18/objects/CreateVendorResponse) objects encapsulating successfully created [Vendor](https://developer.squareup.com/reference/square_2023-10-18/objects/Vendor) objects or error responses for failed attempts. The set is represented by  a collection of idempotency-key/`Vendor`-object or idempotency-key/error-object pairs. The idempotency keys correspond to those specified in the input. [optional]
 */
@property(nonatomic) NSDictionary<SQCreateVendorResponse>* responses;

@end
