#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQUpdateVendorResponse.h"
@protocol SQError;
@class SQError;
@protocol SQUpdateVendorResponse;
@class SQUpdateVendorResponse;



@protocol SQBulkUpdateVendorsResponse
@end

@interface SQBulkUpdateVendorsResponse : SQObject

/* Errors encountered when the request fails. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* A set of [UpdateVendorResponse](https://developer.squareup.com/reference/square_2023-10-18/objects/UpdateVendorResponse) objects encapsulating successfully created [Vendor](https://developer.squareup.com/reference/square_2023-10-18/objects/Vendor) objects or error responses for failed attempts. The set is represented by a collection of `Vendor`-ID/`UpdateVendorResponse`-object or  `Vendor`-ID/error-object pairs. [optional]
 */
@property(nonatomic) NSDictionary<SQUpdateVendorResponse>* responses;

@end
