#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBulkSwapPlanRequest
@end

@interface SQBulkSwapPlanRequest : SQObject

/* The ID of the new subscription plan variation.  This field is required. 
 */
@property(nonatomic) NSString* varNewPlanVariationId;
/* The ID of the plan variation whose subscriptions should be swapped. Active subscriptions using this plan variation will be subscribed to the new plan variation on their next billing day. 
 */
@property(nonatomic) NSString* oldPlanVariationId;
/* The ID of the location to associate with the swapped subscriptions. 
 */
@property(nonatomic) NSString* locationId;

@end
