#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCreateTeamMemberResponse.h"
#import "SQError.h"
@protocol SQCreateTeamMemberResponse;
@class SQCreateTeamMemberResponse;
@protocol SQError;
@class SQError;



@protocol SQBulkCreateTeamMembersResponse
@end

@interface SQBulkCreateTeamMembersResponse : SQObject

/* The successfully created `TeamMember` objects. Each key is the `idempotency_key` that maps to the `CreateTeamMemberRequest`. [optional]
 */
@property(nonatomic) NSDictionary<SQCreateTeamMemberResponse>* teamMembers;
/* The errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
