#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQBulkRetrieveBookingsRequest
@end

@interface SQBulkRetrieveBookingsRequest : SQObject

/* A non-empty list of [Booking](https://developer.squareup.com/reference/square_2023-10-18/objects/Booking) IDs specifying bookings to retrieve. 
 */
@property(nonatomic) NSArray<NSString*>* bookingIds;

@end
