#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQLocationCustomAttributeUpsertRequest.h"
@protocol SQLocationCustomAttributeUpsertRequest;
@class SQLocationCustomAttributeUpsertRequest;



@protocol SQBulkUpsertLocationCustomAttributesRequest
@end

@interface SQBulkUpsertLocationCustomAttributesRequest : SQObject

/* A map containing 1 to 25 individual upsert requests. For each request, provide an arbitrary ID that is unique for this `BulkUpsertLocationCustomAttributes` request and the information needed to create or update a custom attribute. 
 */
@property(nonatomic) NSDictionary<SQLocationCustomAttributeUpsertRequest>* values;

@end
