#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomerCustomAttributeUpsertResponse.h"
#import "SQError.h"
@protocol SQCustomerCustomAttributeUpsertResponse;
@class SQCustomerCustomAttributeUpsertResponse;
@protocol SQError;
@class SQError;



@protocol SQBulkUpsertCustomerCustomAttributesResponse
@end

@interface SQBulkUpsertCustomerCustomAttributesResponse : SQObject

/* A map of responses that correspond to individual upsert requests. Each response has the same ID as the corresponding request and contains either a `customer_id` and `custom_attribute` or an `errors` field. [optional]
 */
@property(nonatomic) NSDictionary<SQCustomerCustomAttributeUpsertResponse>* values;
/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
