#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQUpdateVendorRequest.h"
@protocol SQUpdateVendorRequest;
@class SQUpdateVendorRequest;



@protocol SQBulkUpdateVendorsRequest
@end

@interface SQBulkUpdateVendorsRequest : SQObject

/* A set of [UpdateVendorRequest](https://developer.squareup.com/reference/square_2023-10-18/objects/UpdateVendorRequest) objects encapsulating to-be-updated [Vendor](https://developer.squareup.com/reference/square_2023-10-18/objects/Vendor) objects. The set is represented by  a collection of `Vendor`-ID/`UpdateVendorRequest`-object pairs. 
 */
@property(nonatomic) NSDictionary<SQUpdateVendorRequest>* vendors;

@end
