#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQUpdateTeamMemberRequest.h"
@protocol SQUpdateTeamMemberRequest;
@class SQUpdateTeamMemberRequest;



@protocol SQBulkUpdateTeamMembersRequest
@end

@interface SQBulkUpdateTeamMembersRequest : SQObject

/* The data used to update the `TeamMember` objects. Each key is the `team_member_id` that maps to the `UpdateTeamMemberRequest`. The maximum number of update objects is 25. 
 */
@property(nonatomic) NSDictionary<SQUpdateTeamMemberRequest>* teamMembers;

@end
