#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQBusinessAppointmentSettings
@end

@interface SQBusinessAppointmentSettings : SQObject

/* Types of the location allowed for bookings. [optional]
 */
@property(nonatomic) NSArray<NSString*>* locationTypes;
/* The time unit of the service duration for bookings. [optional]
 */
@property(nonatomic) NSString* alignmentTime;
/* The minimum lead time in seconds before a service can be booked. A booking must be created at least this amount of time before its starting time. [optional]
 */
@property(nonatomic) NSNumber* minBookingLeadTimeSeconds;
/* The maximum lead time in seconds before a service can be booked. A booking must be created at most this amount of time before its starting time. [optional]
 */
@property(nonatomic) NSNumber* maxBookingLeadTimeSeconds;
/* Indicates whether a customer can choose from all available time slots and have a staff member assigned automatically (`true`) or not (`false`). [optional]
 */
@property(nonatomic) NSNumber* anyTeamMemberBookingEnabled;
/* Indicates whether a customer can book multiple services in a single online booking. [optional]
 */
@property(nonatomic) NSNumber* multipleServiceBookingEnabled;
/* Indicates whether the daily appointment limit applies to team members or to business locations. [optional]
 */
@property(nonatomic) NSString* maxAppointmentsPerDayLimitType;
/* The maximum number of daily appointments per team member or per location. [optional]
 */
@property(nonatomic) NSNumber* maxAppointmentsPerDayLimit;
/* The cut-off time in seconds for allowing clients to cancel or reschedule an appointment. [optional]
 */
@property(nonatomic) NSNumber* cancellationWindowSeconds;
/* The flat-fee amount charged for a no-show booking. [optional]
 */
@property(nonatomic) SQMoney* cancellationFeeMoney;
/* The cancellation policy adopted by the seller. [optional]
 */
@property(nonatomic) NSString* cancellationPolicy;
/* The free-form text of the seller's cancellation policy. [optional]
 */
@property(nonatomic) NSString* cancellationPolicyText;
/* Indicates whether customers has an assigned staff member (`true`) or can select s staff member of their choice (`false`). [optional]
 */
@property(nonatomic) NSNumber* skipBookingFlowStaffSelection;

@end
