#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogCustomAttributeValue
@end

@interface SQCatalogCustomAttributeValue : SQObject

/* The name of the custom attribute. [optional]
 */
@property(nonatomic) NSString* name;
/* The string value of the custom attribute.  Populated if `type` = `STRING`. [optional]
 */
@property(nonatomic) NSString* stringValue;
/* The id of the [CatalogCustomAttributeDefinition](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogCustomAttributeDefinition) this value belongs to. [optional]
 */
@property(nonatomic) NSString* customAttributeDefinitionId;
/* A copy of type from the associated `CatalogCustomAttributeDefinition`. [optional]
 */
@property(nonatomic) NSString* type;
/* Populated if `type` = `NUMBER`. Contains a string representation of a decimal number, using a `.` as the decimal separator. [optional]
 */
@property(nonatomic) NSString* numberValue;
/* A `true` or `false` value. Populated if `type` = `BOOLEAN`. [optional]
 */
@property(nonatomic) NSNumber* booleanValue;
/* One or more choices from `allowed_selections`. Populated if `type` = `SELECTION`. [optional]
 */
@property(nonatomic) NSArray<NSString*>* selectionUidValues;
/* If the associated `CatalogCustomAttributeDefinition` object is defined by another application, this key is prefixed by the defining application ID. For example, if the CatalogCustomAttributeDefinition has a key attribute of \"cocoa_brand\" and the defining application ID is \"abcd1234\", this key is \"abcd1234:cocoa_brand\" when the application making the request is different from the application defining the custom attribute definition. Otherwise, the key is simply \"cocoa_brand\". [optional]
 */
@property(nonatomic) NSString* key;

@end
