#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogTax
@end

@interface SQCatalogTax : SQObject

/* The tax's name. This is a searchable attribute for use in applicable query filters, and its value length is of Unicode code points. [optional]
 */
@property(nonatomic) NSString* name;
/* Whether the tax is calculated based on a payment's subtotal or total. [optional]
 */
@property(nonatomic) NSString* calculationPhase;
/* Whether the tax is `ADDITIVE` or `INCLUSIVE`. [optional]
 */
@property(nonatomic) NSString* inclusionType;
/* The percentage of the tax in decimal form, using a `'.'` as the decimal separator and without a `'%'` sign. A value of `7.5` corresponds to 7.5%. For a location-specific tax rate, contact the tax authority of the location or a tax consultant. [optional]
 */
@property(nonatomic) NSString* percentage;
/* If `true`, the fee applies to custom amounts entered into the Square Point of Sale app that are not associated with a particular `CatalogItem`. [optional]
 */
@property(nonatomic) NSNumber* appliesToCustomAmounts;
/* A Boolean flag to indicate whether the tax is displayed as enabled (`true`) in the Square Point of Sale app or not (`false`). [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* The ID of a `CatalogProductSet` object. If set, the tax is applicable to all products in the product set. [optional]
 */
@property(nonatomic) NSString* appliesToProductSetId;

@end
