#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogInfoResponseLimits
@end

@interface SQCatalogInfoResponseLimits : SQObject

/* The maximum number of objects that may appear within a single batch in a `/v2/catalog/batch-upsert` request. [optional]
 */
@property(nonatomic) NSNumber* batchUpsertMaxObjectsPerBatch;
/* The maximum number of objects that may appear across all batches in a `/v2/catalog/batch-upsert` request. [optional]
 */
@property(nonatomic) NSNumber* batchUpsertMaxTotalObjects;
/* The maximum number of object IDs that may appear in a `/v2/catalog/batch-retrieve` request. [optional]
 */
@property(nonatomic) NSNumber* batchRetrieveMaxObjectIds;
/* The maximum number of results that may be returned in a page of a `/v2/catalog/search` response. [optional]
 */
@property(nonatomic) NSNumber* searchMaxPageLimit;
/* The maximum number of object IDs that may be included in a single `/v2/catalog/batch-delete` request. [optional]
 */
@property(nonatomic) NSNumber* batchDeleteMaxObjectIds;
/* The maximum number of item IDs that may be included in a single `/v2/catalog/update-item-taxes` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemTaxesMaxItemIds;
/* The maximum number of tax IDs to be enabled that may be included in a single `/v2/catalog/update-item-taxes` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemTaxesMaxTaxesToEnable;
/* The maximum number of tax IDs to be disabled that may be included in a single `/v2/catalog/update-item-taxes` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemTaxesMaxTaxesToDisable;
/* The maximum number of item IDs that may be included in a single `/v2/catalog/update-item-modifier-lists` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemModifierListsMaxItemIds;
/* The maximum number of modifier list IDs to be enabled that may be included in a single `/v2/catalog/update-item-modifier-lists` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemModifierListsMaxModifierListsToEnable;
/* The maximum number of modifier list IDs to be disabled that may be included in a single `/v2/catalog/update-item-modifier-lists` request. [optional]
 */
@property(nonatomic) NSNumber* updateItemModifierListsMaxModifierListsToDisable;

@end
