#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQCatalogQuickAmount
@end

@interface SQCatalogQuickAmount : SQObject

/* Represents the type of the Quick Amount. 
 */
@property(nonatomic) NSString* type;
/* Represents the actual amount of the Quick Amount with Money type. 
 */
@property(nonatomic) SQMoney* amount;
/* Describes the ranking of the Quick Amount provided by machine learning model, in the range [0, 100]. MANUAL type amount will always have score = 100. [optional]
 */
@property(nonatomic) NSNumber* score;
/* The order in which this Quick Amount should be displayed. [optional]
 */
@property(nonatomic) NSNumber* ordinal;

@end
