#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQCashPaymentDetails
@end

@interface SQCashPaymentDetails : SQObject

/* The amount and currency of the money supplied by the buyer. 
 */
@property(nonatomic) SQMoney* buyerSuppliedMoney;
/* The amount of change due back to the buyer.  This read-only field is calculated from the `amount_money` and `buyer_supplied_money` fields. [optional]
 */
@property(nonatomic) SQMoney* changeBackMoney;

@end
