#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCard.h"
@protocol SQCard;
@class SQCard;



@protocol SQCardRefundDetails
@end

@interface SQCardRefundDetails : SQObject

/* The card's non-confidential details. [optional]
 */
@property(nonatomic) SQCard* card;
/* The method used to enter the card's details for the refund. The method can be `KEYED`, `SWIPED`, `EMV`, `ON_FILE`, or `CONTACTLESS`. [optional]
 */
@property(nonatomic) NSString* entryMethod;

@end
