#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogV1Id
@end

@interface SQCatalogV1Id : SQObject

/* The ID for an object used in the Square API V1, if the object ID differs from the Square API V2 object ID. [optional]
 */
@property(nonatomic) NSString* catalogV1Id;
/* The ID of the `Location` this Connect V1 ID is associated with. [optional]
 */
@property(nonatomic) NSString* locationId;

@end
