#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogCategory
@end

@interface SQCatalogCategory : SQObject

/* The category name. This is a searchable attribute for use in applicable query filters, and its value length is of Unicode code points. [optional]
 */
@property(nonatomic) NSString* name;
/* The IDs of images associated with this `CatalogCategory` instance. Currently these images are not displayed by Square, but are free to be displayed in 3rd party applications. [optional]
 */
@property(nonatomic) NSArray<NSString*>* imageIds;

@end
