#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogQueryRange
@end

@interface SQCatalogQueryRange : SQObject

/* The name of the attribute to be searched. 
 */
@property(nonatomic) NSString* attributeName;
/* The desired minimum value for the search attribute (inclusive). [optional]
 */
@property(nonatomic) NSNumber* attributeMinValue;
/* The desired maximum value for the search attribute (inclusive). [optional]
 */
@property(nonatomic) NSNumber* attributeMaxValue;

@end
