#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogItemOptionValueForItemVariation
@end

@interface SQCatalogItemOptionValueForItemVariation : SQObject

/* The unique id of an item option. [optional]
 */
@property(nonatomic) NSString* itemOptionId;
/* The unique id of the selected value for the item option. [optional]
 */
@property(nonatomic) NSString* itemOptionValueId;

@end
