#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQModifierLocationOverrides.h"
#import "SQMoney.h"
@protocol SQModifierLocationOverrides;
@class SQModifierLocationOverrides;
@protocol SQMoney;
@class SQMoney;



@protocol SQCatalogModifier
@end

@interface SQCatalogModifier : SQObject

/* The modifier name.  This is a searchable attribute for use in applicable query filters, and its value length is of Unicode code points. [optional]
 */
@property(nonatomic) NSString* name;
/* The modifier price. [optional]
 */
@property(nonatomic) SQMoney* priceMoney;
/* Determines where this `CatalogModifier` appears in the `CatalogModifierList`. [optional]
 */
@property(nonatomic) NSNumber* ordinal;
/* The ID of the `CatalogModifierList` associated with this modifier. [optional]
 */
@property(nonatomic) NSString* modifierListId;
/* Location-specific price overrides. [optional]
 */
@property(nonatomic) NSArray<SQModifierLocationOverrides>* locationOverrides;
/* The ID of the image associated with this `CatalogModifier` instance. Currently this image is not displayed by Square, but is free to be displayed in 3rd party applications. [optional]
 */
@property(nonatomic) NSString* imageId;

@end
