#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogQueryItemsForTax
@end

@interface SQCatalogQueryItemsForTax : SQObject

/* A set of `CatalogTax` IDs to be used to find associated `CatalogItem`s. 
 */
@property(nonatomic) NSArray<NSString*>* taxIds;

@end
