#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogQuerySortedAttribute
@end

@interface SQCatalogQuerySortedAttribute : SQObject

/* The attribute whose value is used as the sort key. 
 */
@property(nonatomic) NSString* attributeName;
/* The first attribute value to be returned by the query. Ascending sorts will return only objects with this value or greater, while descending sorts will return only objects with this value or less. If unset, start at the beginning (for ascending sorts) or end (for descending sorts). [optional]
 */
@property(nonatomic) NSString* initialAttributeValue;
/* The desired sort order, `\"ASC\"` (ascending) or `\"DESC\"` (descending). [optional]
 */
@property(nonatomic) NSString* sortOrder;

@end
