#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogItemOptionValue
@end

@interface SQCatalogItemOptionValue : SQObject

/* Unique ID of the associated item option. [optional]
 */
@property(nonatomic) NSString* itemOptionId;
/* Name of this item option value. This is a searchable attribute for use in applicable query filters. [optional]
 */
@property(nonatomic) NSString* name;
/* A human-readable description for the option value. This is a searchable attribute for use in applicable query filters. [optional]
 */
@property(nonatomic) NSString* _description;
/* The HTML-supported hex color for the item option (e.g., \"#ff8d4e85\"). Only displayed if `show_colors` is enabled on the parent `ItemOption`. When left unset, `color` defaults to white (\"#ffffff\") when `show_colors` is enabled on the parent `ItemOption`. [optional]
 */
@property(nonatomic) NSString* color;
/* Determines where this option value appears in a list of option values. [optional]
 */
@property(nonatomic) NSNumber* ordinal;

@end
