#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCatalogInfoResponseLimits.h"
#import "SQError.h"
#import "SQStandardUnitDescriptionGroup.h"
@protocol SQCatalogInfoResponseLimits;
@class SQCatalogInfoResponseLimits;
@protocol SQError;
@class SQError;
@protocol SQStandardUnitDescriptionGroup;
@class SQStandardUnitDescriptionGroup;



@protocol SQCatalogInfoResponse
@end

@interface SQCatalogInfoResponse : SQObject

/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* Limits that apply to this API. [optional]
 */
@property(nonatomic) SQCatalogInfoResponseLimits* limits;
/* Names and abbreviations for standard units. [optional]
 */
@property(nonatomic) SQStandardUnitDescriptionGroup* standardUnitDescriptionGroup;

@end
