#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQCalculateLoyaltyPointsRequest
@end

@interface SQCalculateLoyaltyPointsRequest : SQObject

/* The [order](https://developer.squareup.com/reference/square_2023-10-18/objects/Order) ID for which to calculate the points. Specify this field if your application uses the Orders API to process orders. Otherwise, specify the `transaction_amount_money`. [optional]
 */
@property(nonatomic) NSString* orderId;
/* The purchase amount for which to calculate the points.  Specify this field if your application does not use the Orders API to process orders. Otherwise, specify the `order_id`. [optional]
 */
@property(nonatomic) SQMoney* transactionAmountMoney;
/* The ID of the target [loyalty account](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyAccount). Optionally specify this field if your application uses the Orders API to process orders.  If specified, the `promotion_points` field in the response shows the number of points the buyer would earn from the purchase. In this case, Square uses the account ID to determine whether the promotion's `trigger_limit` (the maximum number of times that a buyer can trigger the promotion) has been reached. If not specified, the `promotion_points` field shows the number of points the purchase qualifies for regardless of the trigger limit. [optional]
 */
@property(nonatomic) NSString* loyaltyAccountId;

@end
