#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQOrder.h"
#import "SQOrderReward.h"
@protocol SQOrder;
@class SQOrder;
@protocol SQOrderReward;
@class SQOrderReward;



@protocol SQCalculateOrderRequest
@end

@interface SQCalculateOrderRequest : SQObject

/* The order to be calculated. Expects the entire order, not a sparse update. 
 */
@property(nonatomic) SQOrder* order;
/* Identifies one or more loyalty reward tiers to apply during the order calculation. The discounts defined by the reward tiers are added to the order only to preview the effect of applying the specified rewards. The rewards do not correspond to actual redemptions; that is, no `reward`s are created. Therefore, the reward `id`s are random strings used only to reference the reward tier. [optional]
 */
@property(nonatomic) NSArray<SQOrderReward>* proposedRewards;

@end
