#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCatalogQuerySet
@end

@interface SQCatalogQuerySet : SQObject

/* The name of the attribute to be searched. Matching of the attribute name is exact. 
 */
@property(nonatomic) NSString* attributeName;
/* The desired values of the search attribute. Matching of the attribute values is exact and case insensitive. A maximum of 250 values may be searched in a request. 
 */
@property(nonatomic) NSArray<NSString*>* attributeValues;

@end
