#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQChangeBillingAnchorDateRequest
@end

@interface SQChangeBillingAnchorDateRequest : SQObject

/* The anchor day for the billing cycle. [optional]
 */
@property(nonatomic) NSNumber* monthlyBillingAnchorDate;
/* The `YYYY-MM-DD`-formatted date when the scheduled `BILLING_ANCHOR_CHANGE` action takes place on the subscription.  When this date is unspecified or falls within the current billing cycle, the billing anchor date is changed immediately. [optional]
 */
@property(nonatomic) NSString* effectiveDate;

@end
