#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQChargeRequestAdditionalRecipient
@end

@interface SQChargeRequestAdditionalRecipient : SQObject

/* The location ID for a recipient (other than the merchant) receiving a portion of the tender. 
 */
@property(nonatomic) NSString* locationId;
/* The description of the additional recipient. 
 */
@property(nonatomic) NSString* _description;
/* The amount of money distributed to the recipient. 
 */
@property(nonatomic) SQMoney* amountMoney;

@end
