#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQCreateDisputeEvidenceTextRequest
@end

@interface SQCreateDisputeEvidenceTextRequest : SQObject

/* A unique key identifying the request. For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency). 
 */
@property(nonatomic) NSString* idempotencyKey;
/* The type of evidence you are uploading. [optional]
 */
@property(nonatomic) NSString* evidenceType;
/* The evidence string. 
 */
@property(nonatomic) NSString* evidenceText;

@end
