#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQSubscription.h"
@protocol SQError;
@class SQError;
@protocol SQSubscription;
@class SQSubscription;



@protocol SQCreateSubscriptionResponse
@end

@interface SQCreateSubscriptionResponse : SQObject

/* Errors encountered during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The newly created subscription.  For more information, see [Subscription object](https://developer.squareup.com/docs/subscriptions-api/manage-subscriptions#subscription-object). [optional]
 */
@property(nonatomic) SQSubscription* subscription;

@end
