#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
@protocol SQError;
@class SQError;



@protocol SQCreateMobileAuthorizationCodeResponse
@end

@interface SQCreateMobileAuthorizationCodeResponse : SQObject

/* The generated authorization code that connects a mobile application instance to a Square account. [optional]
 */
@property(nonatomic) NSString* authorizationCode;
/* The timestamp when `authorization_code` expires, in [RFC 3339](https://tools.ietf.org/html/rfc3339) format (for example, \"2016-09-04T23:59:33.123Z\"). [optional]
 */
@property(nonatomic) NSString* expiresAt;
/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
