#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQDeviceCode.h"
@protocol SQDeviceCode;
@class SQDeviceCode;



@protocol SQCreateDeviceCodeRequest
@end

@interface SQCreateDeviceCodeRequest : SQObject

/* A unique string that identifies this CreateDeviceCode request. Keys can be any valid string but must be unique for every CreateDeviceCode request.  See [Idempotency keys](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency) for more information. 
 */
@property(nonatomic) NSString* idempotencyKey;
/* The device code to create. 
 */
@property(nonatomic) SQDeviceCode* deviceCode;

@end
