#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQTerminalCheckout.h"
@protocol SQTerminalCheckout;
@class SQTerminalCheckout;



@protocol SQCreateTerminalCheckoutRequest
@end

@interface SQCreateTerminalCheckoutRequest : SQObject

/* A unique string that identifies this `CreateCheckout` request. Keys can be any valid string but must be unique for every `CreateCheckout` request.  See [Idempotency keys](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency) for more information. 
 */
@property(nonatomic) NSString* idempotencyKey;
/* The checkout to create. 
 */
@property(nonatomic) SQTerminalCheckout* checkout;

@end
