#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomerGroup.h"
@protocol SQCustomerGroup;
@class SQCustomerGroup;



@protocol SQCreateCustomerGroupRequest
@end

@interface SQCreateCustomerGroupRequest : SQObject

/* The idempotency key for the request. For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency). [optional]
 */
@property(nonatomic) NSString* idempotencyKey;
/* The customer group to create. 
 */
@property(nonatomic) SQCustomerGroup* group;

@end
