#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCard.h"
@protocol SQCard;
@class SQCard;



@protocol SQCreateCardRequest
@end

@interface SQCreateCardRequest : SQObject

/* A unique string that identifies this CreateCard request. Keys can be any valid string and must be unique for every request.  Max: 45 characters  See [Idempotency keys](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency) for more information. 
 */
@property(nonatomic) NSString* idempotencyKey;
/* The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id. 
 */
@property(nonatomic) NSString* sourceId;
/* An identifying token generated by [Payments.verifyBuyer()](https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer). Verification tokens encapsulate customer device information and 3-D Secure challenge results to indicate that Square has verified the buyer identity.  See the [SCA Overview](https://developer.squareup.com/docs/sca-overview). [optional]
 */
@property(nonatomic) NSString* verificationToken;
/* Payment details associated with the card to be stored. 
 */
@property(nonatomic) SQCard* card;

@end
