#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQLoyaltyAccount.h"
@protocol SQLoyaltyAccount;
@class SQLoyaltyAccount;



@protocol SQCreateLoyaltyAccountRequest
@end

@interface SQCreateLoyaltyAccountRequest : SQObject

/* The loyalty account to create. 
 */
@property(nonatomic) SQLoyaltyAccount* loyaltyAccount;
/* A unique string that identifies this `CreateLoyaltyAccount` request.  Keys can be any valid string, but must be unique for every request. 
 */
@property(nonatomic) NSString* idempotencyKey;

@end
