#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQTeamMember.h"
@protocol SQError;
@class SQError;
@protocol SQTeamMember;
@class SQTeamMember;



@protocol SQCreateTeamMemberResponse
@end

@interface SQCreateTeamMemberResponse : SQObject

/* The successfully created `TeamMember` object. [optional]
 */
@property(nonatomic) SQTeamMember* teamMember;
/* The errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
