#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomerFilter.h"
#import "SQCustomerSort.h"
@protocol SQCustomerFilter;
@class SQCustomerFilter;
@protocol SQCustomerSort;
@class SQCustomerSort;



@protocol SQCustomerQuery
@end

@interface SQCustomerQuery : SQObject

/* The filtering criteria for the search query. A query can contain multiple filters in any combination. Multiple filters are combined as `AND` statements.  __Note:__ Combining multiple filters as `OR` statements is not supported. Instead, send multiple single-filter searches and join the result sets. [optional]
 */
@property(nonatomic) SQCustomerFilter* filter;
/* Sorting criteria for query results. The default behavior is to sort  customers alphabetically by `given_name` and `family_name`. [optional]
 */
@property(nonatomic) SQCustomerSort* sort;

@end
