#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomerTextFilter.h"
@protocol SQCustomerTextFilter;
@class SQCustomerTextFilter;



@protocol SQCustomerAddressFilter
@end

@interface SQCustomerAddressFilter : SQObject

/* The postal code to search for. Only an `exact` match is supported. [optional]
 */
@property(nonatomic) SQCustomerTextFilter* postalCode;
/* The country code to search for. [optional]
 */
@property(nonatomic) NSString* country;

@end
