#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQRange.h"
@protocol SQRange;
@class SQRange;



@protocol SQCustomAttributeFilter
@end

@interface SQCustomAttributeFilter : SQObject

/* A query expression to filter items or item variations by matching their custom attributes' `custom_attribute_definition_id` property value against the the specified id. Exactly one of `custom_attribute_definition_id` or `key` must be specified. [optional]
 */
@property(nonatomic) NSString* customAttributeDefinitionId;
/* A query expression to filter items or item variations by matching their custom attributes' `key` property value against the specified key. Exactly one of `custom_attribute_definition_id` or `key` must be specified. [optional]
 */
@property(nonatomic) NSString* key;
/* A query expression to filter items or item variations by matching their custom attributes' `string_value`  property value against the specified text. Exactly one of `string_filter`, `number_filter`, `selection_uids_filter`, or `bool_filter` must be specified. [optional]
 */
@property(nonatomic) NSString* stringFilter;
/* A query expression to filter items or item variations with their custom attributes containing a number value within the specified range. Exactly one of `string_filter`, `number_filter`, `selection_uids_filter`, or `bool_filter` must be specified. [optional]
 */
@property(nonatomic) SQRange* numberFilter;
/* A query expression to filter items or item variations by matching  their custom attributes' `selection_uid_values` values against the specified selection uids. Exactly one of `string_filter`, `number_filter`, `selection_uids_filter`, or `bool_filter` must be specified. [optional]
 */
@property(nonatomic) NSArray<NSString*>* selectionUidsFilter;
/* A query expression to filter items or item variations by matching their custom attributes' `boolean_value` property values against the specified Boolean expression. Exactly one of `string_filter`, `number_filter`, `selection_uids_filter`, or `bool_filter` must be specified. [optional]
 */
@property(nonatomic) NSNumber* boolFilter;

@end
