#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomerCustomAttributeFilterValue.h"
#import "SQTimeRange.h"
@protocol SQCustomerCustomAttributeFilterValue;
@class SQCustomerCustomAttributeFilterValue;
@protocol SQTimeRange;
@class SQTimeRange;



@protocol SQCustomerCustomAttributeFilter
@end

@interface SQCustomerCustomAttributeFilter : SQObject

/* The `key` of the [custom attribute](https://developer.squareup.com/reference/square_2023-10-18/objects/CustomAttribute) to filter by. The key is the identifier of the custom attribute (and the corresponding custom attribute definition) and can be retrieved using the [Customer Custom Attributes API](https://developer.squareup.com/reference/square_2023-10-18/customer-custom-attributes-api). 
 */
@property(nonatomic) NSString* key;
/* A filter that corresponds to the data type of the target custom attribute. For example, provide the `phone` filter to search based on the value of a `PhoneNumber`-type custom attribute. The data type is specified by the schema field of the custom attribute definition, which can be retrieved using the [Customer Custom Attributes API](https://developer.squareup.com/reference/square_2023-10-18/customer-custom-attributes-api).  You must provide this `filter` field, the `updated_at` field, or both. [optional]
 */
@property(nonatomic) SQCustomerCustomAttributeFilterValue* filter;
/* The date range for when the custom attribute was last updated. The date range can include `start_at`, `end_at`, or both. Range boundaries are inclusive. Dates are specified as RFC 3339 timestamps.  You must provide this `updated_at` field, the `filter` field, or both. [optional]
 */
@property(nonatomic) SQTimeRange* updatedAt;

@end
