#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQDeviceComponentDetailsApplicationDetails
@end

@interface SQDeviceComponentDetailsApplicationDetails : SQObject

/* The type of application. [optional]
 */
@property(nonatomic) NSString* applicationType;
/* The version of the application. [optional]
 */
@property(nonatomic) NSString* version;
/* The location_id of the session for the application. [optional]
 */
@property(nonatomic) NSString* sessionLocation;
/* The id of the device code that was used to log in to the device. [optional]
 */
@property(nonatomic) NSString* deviceCodeId;

@end
