#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQDeviceComponentDetailsEthernetDetails
@end

@interface SQDeviceComponentDetailsEthernetDetails : SQObject

/* A boolean to represent whether the Ethernet interface is currently active. [optional]
 */
@property(nonatomic) NSNumber* active;
/* The string representation of the device’s IPv4 address. [optional]
 */
@property(nonatomic) NSString* ipAddressV4;

@end
