#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMeasurement.h"
@protocol SQMeasurement;
@class SQMeasurement;



@protocol SQDeviceComponentDetailsWiFiDetails
@end

@interface SQDeviceComponentDetailsWiFiDetails : SQObject

/* A boolean to represent whether the WiFI interface is currently active. [optional]
 */
@property(nonatomic) NSNumber* active;
/* The name of the connected WIFI network. [optional]
 */
@property(nonatomic) NSString* ssid;
/* The string representation of the device’s IPv4 address. [optional]
 */
@property(nonatomic) NSString* ipAddressV4;
/* The security protocol for a secure connection (e.g. WPA2). None provided if the connection is unsecured. [optional]
 */
@property(nonatomic) NSString* secureConnection;
/* A representation of signal strength of the WIFI network connection. [optional]
 */
@property(nonatomic) SQMeasurement* signalStrength;

@end
