#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQDeleteInvoiceRequest
@end

@interface SQDeleteInvoiceRequest : SQObject

/* The version of the [invoice](https://developer.squareup.com/reference/square_2023-10-18/objects/Invoice) to delete. If you do not know the version, you can call [GetInvoice](https://developer.squareup.com/reference/square_2023-10-18/invoices-api/get-invoice) or  [ListInvoices](https://developer.squareup.com/reference/square_2023-10-18/invoices-api/list-invoices). [optional]
 */
@property(nonatomic) NSNumber* version;

@end
