#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQDeviceMetadata
@end

@interface SQDeviceMetadata : SQObject

/* The Terminal’s remaining battery percentage, between 1-100. [optional]
 */
@property(nonatomic) NSString* batteryPercentage;
/* The current charging state of the Terminal. Options: `CHARGING`, `NOT_CHARGING` [optional]
 */
@property(nonatomic) NSString* chargingState;
/* The ID of the Square seller business location associated with the Terminal. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The ID of the Square merchant account that is currently signed-in to the Terminal. [optional]
 */
@property(nonatomic) NSString* merchantId;
/* The Terminal’s current network connection type. Options: `WIFI`, `ETHERNET` [optional]
 */
@property(nonatomic) NSString* networkConnectionType;
/* The country in which the Terminal is authorized to take payments. [optional]
 */
@property(nonatomic) NSString* paymentRegion;
/* The unique identifier assigned to the Terminal, which can be found on the lower back of the device. [optional]
 */
@property(nonatomic) NSString* serialNumber;
/* The current version of the Terminal’s operating system. [optional]
 */
@property(nonatomic) NSString* osVersion;
/* The current version of the application running on the Terminal. [optional]
 */
@property(nonatomic) NSString* appVersion;
/* The name of the Wi-Fi network to which the Terminal is connected. [optional]
 */
@property(nonatomic) NSString* wifiNetworkName;
/* The signal strength of the Wi-FI network connection. Options: `POOR`, `FAIR`, `GOOD`, `EXCELLENT` [optional]
 */
@property(nonatomic) NSString* wifiNetworkStrength;
/* The IP address of the Terminal. [optional]
 */
@property(nonatomic) NSString* ipAddress;

@end
