#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
@protocol SQError;
@class SQError;



@protocol SQDeletePaymentLinkResponse
@end

@interface SQDeletePaymentLinkResponse : SQObject

/*  [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The ID of the link that is deleted. [optional]
 */
@property(nonatomic) NSString* _id;
/* The ID of the order that is canceled. When a payment link is deleted, Square updates the the `state` (of the order that the checkout link created) to CANCELED. [optional]
 */
@property(nonatomic) NSString* cancelledOrderId;

@end
