#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQDisputeEvidenceFile.h"
@protocol SQDisputeEvidenceFile;
@class SQDisputeEvidenceFile;



@protocol SQDisputeEvidence
@end

@interface SQDisputeEvidence : SQObject

/* The Square-generated ID of the evidence. [optional]
 */
@property(nonatomic) NSString* evidenceId;
/* The Square-generated ID of the evidence. [optional]
 */
@property(nonatomic) NSString* _id;
/* The ID of the dispute the evidence is associated with. [optional]
 */
@property(nonatomic) NSString* disputeId;
/* Image, PDF, TXT [optional]
 */
@property(nonatomic) SQDisputeEvidenceFile* evidenceFile;
/* Raw text [optional]
 */
@property(nonatomic) NSString* evidenceText;
/* The time when the evidence was uploaded, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* uploadedAt;
/* The type of the evidence. [optional]
 */
@property(nonatomic) NSString* evidenceType;

@end
