#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCashAppDetails.h"
@protocol SQCashAppDetails;
@class SQCashAppDetails;



@protocol SQDigitalWalletDetails
@end

@interface SQDigitalWalletDetails : SQObject

/* The status of the `WALLET` payment. The status can be `AUTHORIZED`, `CAPTURED`, `VOIDED`, or `FAILED`. [optional]
 */
@property(nonatomic) NSString* status;
/* The brand used for the `WALLET` payment. The brand can be `CASH_APP`, `PAYPAY` or `UNKNOWN`. [optional]
 */
@property(nonatomic) NSString* brand;
/* Brand-specific details for payments with the `brand` of `CASH_APP`. [optional]
 */
@property(nonatomic) SQCashAppDetails* cashAppDetails;

@end
