#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQEmployee
@end

@interface SQEmployee : SQObject

/* UUID for this object. [optional]
 */
@property(nonatomic) NSString* _id;
/* The employee's first name. [optional]
 */
@property(nonatomic) NSString* firstName;
/* The employee's last name. [optional]
 */
@property(nonatomic) NSString* lastName;
/* The employee's email address [optional]
 */
@property(nonatomic) NSString* email;
/* The employee's phone number in E.164 format, i.e. \"+12125554250\" [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/* A list of location IDs where this employee has access to. [optional]
 */
@property(nonatomic) NSArray<NSString*>* locationIds;
/* Specifies the status of the employees being fetched. [optional]
 */
@property(nonatomic) NSString* status;
/* Whether this employee is the owner of the merchant. Each merchant has one owner employee, and that employee has full authority over the account. [optional]
 */
@property(nonatomic) NSNumber* isOwner;
/* A read-only timestamp in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* A read-only timestamp in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* updatedAt;

@end
