#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQFilterValue
@end

@interface SQFilterValue : SQObject

/* A list of terms that must be present on the field of the resource. [optional]
 */
@property(nonatomic) NSArray<NSString*>* all;
/* A list of terms where at least one of them must be present on the field of the resource. [optional]
 */
@property(nonatomic) NSArray<NSString*>* any;
/* A list of terms that must not be present on the field the resource [optional]
 */
@property(nonatomic) NSArray<NSString*>* none;

@end
