#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQAddress.h"
@protocol SQAddress;
@class SQAddress;



@protocol SQFulfillmentRecipient
@end

@interface SQFulfillmentRecipient : SQObject

/* The ID of the customer associated with the fulfillment.  If `customer_id` is provided, the fulfillment recipient's `display_name`, `email_address`, and `phone_number` are automatically populated from the targeted customer profile. If these fields are set in the request, the request values override the information from the customer profile. If the targeted customer profile does not contain the necessary information and these fields are left unset, the request results in an error. [optional]
 */
@property(nonatomic) NSString* customerId;
/* The display name of the fulfillment recipient. This field is required.  If provided, the display name overrides the corresponding customer profile value indicated by `customer_id`. [optional]
 */
@property(nonatomic) NSString* displayName;
/* The email address of the fulfillment recipient.  If provided, the email address overrides the corresponding customer profile value indicated by `customer_id`. [optional]
 */
@property(nonatomic) NSString* emailAddress;
/* The phone number of the fulfillment recipient. This field is required.  If provided, the phone number overrides the corresponding customer profile value indicated by `customer_id`. [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/* The address of the fulfillment recipient. This field is required.  If provided, the address overrides the corresponding customer profile value indicated by `customer_id`. [optional]
 */
@property(nonatomic) SQAddress* address;

@end
