#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQBankAccount.h"
#import "SQError.h"
@protocol SQBankAccount;
@class SQBankAccount;
@protocol SQError;
@class SQError;



@protocol SQGetBankAccountByV1IdResponse
@end

@interface SQGetBankAccountByV1IdResponse : SQObject

/* Information on errors encountered during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The requested `BankAccount` object. [optional]
 */
@property(nonatomic) SQBankAccount* bankAccount;

@end
