#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQGiftCard
@end

@interface SQGiftCard : SQObject

/* The Square-assigned ID of the gift card. [optional]
 */
@property(nonatomic) NSString* _id;
/* The gift card type. 
 */
@property(nonatomic) NSString* type;
/* The source that generated the gift card account number (GAN). The default value is `SQUARE`. [optional]
 */
@property(nonatomic) NSString* ganSource;
/* The current gift card state. [optional]
 */
@property(nonatomic) NSString* state;
/* The current gift card balance. This balance is always greater than or equal to zero. [optional]
 */
@property(nonatomic) SQMoney* balanceMoney;
/* The gift card account number (GAN). Buyers can use the GAN to make purchases or check  the gift card balance. [optional]
 */
@property(nonatomic) NSString* gan;
/* The timestamp when the gift card was created, in RFC 3339 format.  In the case of a digital gift card, it is the time when you create a card  (using the Square Point of Sale application, Seller Dashboard, or Gift Cards API).   In the case of a plastic gift card, it is the time when Square associates the card with the  seller at the time of activation. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The IDs of the [customer profiles](https://developer.squareup.com/reference/square_2023-10-18/objects/Customer) to whom this gift card is linked. [optional]
 */
@property(nonatomic) NSArray<NSString*>* customerIds;

@end
