#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQGiftCardActivityUnlinkedActivityRefund
@end

@interface SQGiftCardActivityUnlinkedActivityRefund : SQObject

/* The amount added to the gift card for the refund. This value is a positive integer. 
 */
@property(nonatomic) SQMoney* amountMoney;
/* A client-specified ID that associates the gift card activity with an entity in another system. [optional]
 */
@property(nonatomic) NSString* referenceId;
/* The ID of the refunded payment. This field is not used starting in Square version 2022-06-16. [optional]
 */
@property(nonatomic) NSString* paymentId;

@end
