#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQGiftCardActivityRefund
@end

@interface SQGiftCardActivityRefund : SQObject

/* The ID of the refunded `REDEEM` gift card activity. Square populates this field if the  `payment_id` in the corresponding [RefundPayment](https://developer.squareup.com/reference/square_2023-10-18/refunds-api/refund-payment) request  represents a redemption made by the same gift card. Note that you must use `RefundPayment`  to refund a gift card payment to the same gift card if the payment was processed by Square.  For applications that use a custom payment processing system, this field is required when creating a `REFUND` activity. The provided `REDEEM` activity ID must be linked to the same gift card. [optional]
 */
@property(nonatomic) NSString* redeemActivityId;
/* The amount added to the gift card for the refund. This value is a positive integer.  This field is required when creating a `REFUND` activity. The amount can represent a full or partial refund. [optional]
 */
@property(nonatomic) SQMoney* amountMoney;
/* A client-specified ID that associates the gift card activity with an entity in another system. [optional]
 */
@property(nonatomic) NSString* referenceId;
/* The ID of the refunded payment. Square populates this field if the refund is for a  payment processed by Square and one of the following conditions is true:  - The Refunds API is used to refund a gift card payment to the same gift card. - A seller initiated the refund from Square Point of Sale or the Seller Dashboard. The payment source can be the  same gift card or a cross-tender payment from a credit card or a different gift card. [optional]
 */
@property(nonatomic) NSString* paymentId;

@end
