#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQInfoCode.h"
@protocol SQInfoCode;
@class SQInfoCode;



@protocol SQInfo
@end

@interface SQInfo : SQObject

/* A human-readable explanation for the event. [optional]
 */
@property(nonatomic) NSString* detail;
/* An info code indicating the subscription event that occurred. [optional]
 */
@property(nonatomic) SQInfoCode* code;

@end
