#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQInvoicePaymentReminder
@end

@interface SQInvoicePaymentReminder : SQObject

/* A Square-assigned ID that uniquely identifies the reminder within the `InvoicePaymentRequest`. [optional]
 */
@property(nonatomic) NSString* uid;
/* The number of days before (a negative number) or after (a positive number) the payment request `due_date` when the reminder is sent. For example, -3 indicates that the reminder should be sent 3 days before the payment request `due_date`. [optional]
 */
@property(nonatomic) NSNumber* relativeScheduledDays;
/* The reminder message. [optional]
 */
@property(nonatomic) NSString* message;
/* The status of the reminder. [optional]
 */
@property(nonatomic) NSString* status;
/* If sent, the timestamp when the reminder was sent, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* sentAt;

@end
