#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQInvoiceFilter.h"
#import "SQInvoiceSort.h"
@protocol SQInvoiceFilter;
@class SQInvoiceFilter;
@protocol SQInvoiceSort;
@class SQInvoiceSort;



@protocol SQInvoiceQuery
@end

@interface SQInvoiceQuery : SQObject

/* Query filters to apply in searching invoices.  For more information, see [Search for invoices](https://developer.squareup.com/docs/invoices-api/retrieve-list-search-invoices#search-invoices). 
 */
@property(nonatomic) SQInvoiceFilter* filter;
/* Describes the sort order for the search result. [optional]
 */
@property(nonatomic) SQInvoiceSort* sort;

@end
