#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQListWorkweekConfigsRequest
@end

@interface SQListWorkweekConfigsRequest : SQObject

/* The maximum number of `WorkweekConfigs` results to return per page. [optional]
 */
@property(nonatomic) NSNumber* limit;
/* A pointer to the next page of `WorkweekConfig` results to fetch. [optional]
 */
@property(nonatomic) NSString* cursor;

@end
