#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQListGiftCardActivitiesRequest
@end

@interface SQListGiftCardActivitiesRequest : SQObject

/* If a gift card ID is provided, the endpoint returns activities related  to the specified gift card. Otherwise, the endpoint returns all gift card activities for  the seller. [optional]
 */
@property(nonatomic) NSString* giftCardId;
/* If a [type](https://developer.squareup.com/reference/square_2023-10-18/objects/GiftCardActivityType) is provided, the endpoint returns gift card activities of the specified type.  Otherwise, the endpoint returns all types of gift card activities. [optional]
 */
@property(nonatomic) NSString* type;
/* If a location ID is provided, the endpoint returns gift card activities for the specified location.  Otherwise, the endpoint returns gift card activities for all locations. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The timestamp for the beginning of the reporting period, in RFC 3339 format. This start time is inclusive. The default value is the current time minus one year. [optional]
 */
@property(nonatomic) NSString* beginTime;
/* The timestamp for the end of the reporting period, in RFC 3339 format. This end time is inclusive. The default value is the current time. [optional]
 */
@property(nonatomic) NSString* endTime;
/* If a limit is provided, the endpoint returns the specified number  of results (or fewer) per page. The maximum value is 100. The default value is 50. For more information, see [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination). [optional]
 */
@property(nonatomic) NSNumber* limit;
/* A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of results for the original query. If a cursor is not provided, the endpoint returns the first page of the results. For more information, see [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination). [optional]
 */
@property(nonatomic) NSString* cursor;
/* The order in which the endpoint returns the activities, based on `created_at`. - `ASC` - Oldest to newest. - `DESC` - Newest to oldest (default). [optional]
 */
@property(nonatomic) NSString* sortOrder;

@end
