#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQListDevicesRequest
@end

@interface SQListDevicesRequest : SQObject

/* A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of results for the original query. See [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination) for more information. [optional]
 */
@property(nonatomic) NSString* cursor;
/* The order in which results are listed. - `ASC` - Oldest to newest. - `DESC` - Newest to oldest (default). [optional]
 */
@property(nonatomic) NSString* sortOrder;
/* The number of results to return in a single page. [optional]
 */
@property(nonatomic) NSNumber* limit;
/* If present, only returns devices at the target location. [optional]
 */
@property(nonatomic) NSString* locationId;

@end
