#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQTeamMemberBookingProfile.h"
@protocol SQError;
@class SQError;
@protocol SQTeamMemberBookingProfile;
@class SQTeamMemberBookingProfile;



@protocol SQListTeamMemberBookingProfilesResponse
@end

@interface SQListTeamMemberBookingProfilesResponse : SQObject

/* The list of team member booking profiles. The results are returned in the ascending order of the time when the team member booking profiles were last updated. Multiple booking profiles updated at the same time are further sorted in the ascending order of their IDs. [optional]
 */
@property(nonatomic) NSArray<SQTeamMemberBookingProfile>* teamMemberBookingProfiles;
/* The pagination cursor to be used in the subsequent request to get the next page of the results. Stop retrieving the next page of the results when the cursor is not set. [optional]
 */
@property(nonatomic) NSString* cursor;
/* Errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
