#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQListWebhookSubscriptionsRequest
@end

@interface SQListWebhookSubscriptionsRequest : SQObject

/* A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for your original query.  For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination). [optional]
 */
@property(nonatomic) NSString* cursor;
/* Includes disabled [Subscription](https://developer.squareup.com/reference/square_2023-10-18/objects/WebhookSubscription)s. By default, all enabled [Subscription](https://developer.squareup.com/reference/square_2023-10-18/objects/WebhookSubscription)s are returned. [optional]
 */
@property(nonatomic) NSNumber* includeDisabled;
/* Sorts the returned list by when the [Subscription](https://developer.squareup.com/reference/square_2023-10-18/objects/WebhookSubscription) was created with the specified order. This field defaults to ASC. [optional]
 */
@property(nonatomic) NSString* sortOrder;
/* The maximum number of results to be returned in a single page. It is possible to receive fewer results than the specified limit on a given page. The default value of 100 is also the maximum allowed value.  Default: 100 [optional]
 */
@property(nonatomic) NSNumber* limit;

@end
