#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQBooking.h"
#import "SQError.h"
@protocol SQBooking;
@class SQBooking;
@protocol SQError;
@class SQError;



@protocol SQListBookingsResponse
@end

@interface SQListBookingsResponse : SQObject

/* The list of targeted bookings. [optional]
 */
@property(nonatomic) NSArray<SQBooking>* bookings;
/* The pagination cursor to be used in the subsequent request to get the next page of the results. Stop retrieving the next page of the results when the cursor is not set. [optional]
 */
@property(nonatomic) NSString* cursor;
/* Errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
