#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCashDrawerShiftEvent.h"
#import "SQError.h"
@protocol SQCashDrawerShiftEvent;
@class SQCashDrawerShiftEvent;
@protocol SQError;
@class SQError;



@protocol SQListCashDrawerShiftEventsResponse
@end

@interface SQListCashDrawerShiftEventsResponse : SQObject

/* Opaque cursor for fetching the next page. Cursor is not present in the last page of results. [optional]
 */
@property(nonatomic) NSString* cursor;
/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* All of the events (payments, refunds, etc.) for a cash drawer during the shift. [optional]
 */
@property(nonatomic) NSArray<SQCashDrawerShiftEvent>* cashDrawerShiftEvents;

@end
