#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQLoyaltyPromotionIncentivePointsAdditionData.h"
#import "SQLoyaltyPromotionIncentivePointsMultiplierData.h"
@protocol SQLoyaltyPromotionIncentivePointsAdditionData;
@class SQLoyaltyPromotionIncentivePointsAdditionData;
@protocol SQLoyaltyPromotionIncentivePointsMultiplierData;
@class SQLoyaltyPromotionIncentivePointsMultiplierData;



@protocol SQLoyaltyPromotionIncentive
@end

@interface SQLoyaltyPromotionIncentive : SQObject

/* The type of points incentive. 
 */
@property(nonatomic) NSString* type;
/* Additional data for a `POINTS_MULTIPLIER` incentive type. [optional]
 */
@property(nonatomic) SQLoyaltyPromotionIncentivePointsMultiplierData* pointsMultiplierData;
/* Additional data for a `POINTS_ADDITION` incentive type. [optional]
 */
@property(nonatomic) SQLoyaltyPromotionIncentivePointsAdditionData* pointsAdditionData;

@end
