#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQLoyaltyReward
@end

@interface SQLoyaltyReward : SQObject

/* The Square-assigned ID of the loyalty reward. [optional]
 */
@property(nonatomic) NSString* _id;
/* The status of a loyalty reward. [optional]
 */
@property(nonatomic) NSString* status;
/* The Square-assigned ID of the [loyalty account](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyAccount) to which the reward belongs. 
 */
@property(nonatomic) NSString* loyaltyAccountId;
/* The Square-assigned ID of the [reward tier](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyProgramRewardTier) used to create the reward. 
 */
@property(nonatomic) NSString* rewardTierId;
/* The number of loyalty points used for the reward. [optional]
 */
@property(nonatomic) NSNumber* points;
/* The Square-assigned ID of the [order](https://developer.squareup.com/reference/square_2023-10-18/objects/Order) to which the reward is attached. [optional]
 */
@property(nonatomic) NSString* orderId;
/* The timestamp when the reward was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The timestamp when the reward was last updated, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* updatedAt;
/* The timestamp when the reward was redeemed, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* redeemedAt;

@end
