#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQLoyaltyEventAccumulatePoints
@end

@interface SQLoyaltyEventAccumulatePoints : SQObject

/* The ID of the [loyalty program](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyProgram). [optional]
 */
@property(nonatomic) NSString* loyaltyProgramId;
/* The number of points accumulated by the event. [optional]
 */
@property(nonatomic) NSNumber* points;
/* The ID of the [order](https://developer.squareup.com/reference/square_2023-10-18/objects/Order) for which the buyer accumulated the points. This field is returned only if the Orders API is used to process orders. [optional]
 */
@property(nonatomic) NSString* orderId;

@end
