#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQLoyaltyProgramAccrualRuleItemVariationData
@end

@interface SQLoyaltyProgramAccrualRuleItemVariationData : SQObject

/* The ID of the `ITEM_VARIATION` [catalog object](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogObject) that buyers can purchase to earn points. 
 */
@property(nonatomic) NSString* itemVariationId;

@end
