#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQLoyaltyEventAdjustPoints
@end

@interface SQLoyaltyEventAdjustPoints : SQObject

/* The Square-assigned ID of the [loyalty program](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyProgram). [optional]
 */
@property(nonatomic) NSString* loyaltyProgramId;
/* The number of points added or removed. 
 */
@property(nonatomic) NSNumber* points;
/* The reason for the adjustment of points. [optional]
 */
@property(nonatomic) NSString* reason;

@end
