#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQLoyaltyEventFilter.h"
@protocol SQLoyaltyEventFilter;
@class SQLoyaltyEventFilter;



@protocol SQLoyaltyEventQuery
@end

@interface SQLoyaltyEventQuery : SQObject

/* The query filter criteria. [optional]
 */
@property(nonatomic) SQLoyaltyEventFilter* filter;

@end
