#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomAttribute.h"
#import "SQError.h"
@protocol SQCustomAttribute;
@class SQCustomAttribute;
@protocol SQError;
@class SQError;



@protocol SQLocationCustomAttributeUpsertResponse
@end

@interface SQLocationCustomAttributeUpsertResponse : SQObject

/* The ID of the location associated with the custom attribute. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The new or updated custom attribute. [optional]
 */
@property(nonatomic) SQCustomAttribute* customAttribute;
/* Any errors that occurred while processing the individual request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
