#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQMeasurementUnitCustom
@end

@interface SQMeasurementUnitCustom : SQObject

/* The name of the custom unit, for example \"bushel\". 
 */
@property(nonatomic) NSString* name;
/* The abbreviation of the custom unit, such as \"bsh\" (bushel). This appears in the cart for the Point of Sale app, and in reports. 
 */
@property(nonatomic) NSString* abbreviation;

@end
