#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
@protocol SQError;
@class SQError;



@protocol SQObtainTokenResponse
@end

@interface SQObtainTokenResponse : SQObject

/* A valid OAuth access token. OAuth access tokens are 64 bytes long. Provide the access token in a header with every request to Connect API endpoints. For more information, see [OAuth API: Walkthrough](https://developer.squareup.com/docs/oauth-api/walkthrough). [optional]
 */
@property(nonatomic) NSString* accessToken;
/* This value is always _bearer_. [optional]
 */
@property(nonatomic) NSString* tokenType;
/* The date when the `access_token` expires, in [ISO 8601](http://www.iso.org/iso/home/standards/iso8601.htm) format. [optional]
 */
@property(nonatomic) NSString* expiresAt;
/* The ID of the authorizing merchant's business. [optional]
 */
@property(nonatomic) NSString* merchantId;
/* __LEGACY FIELD__. The ID of a subscription plan the merchant signed up for. The ID is only present if the merchant signed up for a subscription plan during authorization. [optional]
 */
@property(nonatomic) NSString* subscriptionId;
/* __LEGACY FIELD__. The ID of the subscription plan the merchant signed up for. The ID is only present if the merchant signed up for a subscription plan during authorization. [optional]
 */
@property(nonatomic) NSString* planId;
/* The OpenID token belonging to this person. This token is only present if the OPENID scope is included in the authorization request. [optional]
 */
@property(nonatomic) NSString* idToken;
/* A refresh token. OAuth refresh tokens are 64 bytes long. For more information, see [Refresh, Revoke, and Limit the Scope of OAuth Tokens](https://developer.squareup.com/docs/oauth-api/refresh-revoke-limit-scope). [optional]
 */
@property(nonatomic) NSString* refreshToken;
/* A Boolean indicating that the access token is a short-lived access token. The short-lived access token returned in the response expires in 24 hours. [optional]
 */
@property(nonatomic) NSNumber* shortLived;
/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The date when the `refresh_token` expires, in [ISO 8601](http://www.iso.org/iso/home/standards/iso8601.htm) format. [optional]
 */
@property(nonatomic) NSString* refreshTokenExpiresAt;

@end
