#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQOrderFulfillmentPickupDetailsCurbsidePickupDetails
@end

@interface SQOrderFulfillmentPickupDetailsCurbsidePickupDetails : SQObject

/* Specific details for curbside pickup, such as parking number and vehicle model. [optional]
 */
@property(nonatomic) NSString* curbsideDetails;
/* The [timestamp](https://developer.squareup.com/docs/build-basics/working-with-dates) indicating when the buyer arrived and is waiting for pickup. The timestamp must be in RFC 3339 format (for example, \"2016-09-04T23:59:33.123Z\"). [optional]
 */
@property(nonatomic) NSString* buyerArrivedAt;

@end
