#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQOrderUpdated.h"
@protocol SQOrderUpdated;
@class SQOrderUpdated;



@protocol SQOrderUpdatedObject
@end

@interface SQOrderUpdatedObject : SQObject

/* Information about the updated order. [optional]
 */
@property(nonatomic) SQOrderUpdated* orderUpdated;

@end
