#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
#import "SQOrderLineItemAppliedDiscount.h"
#import "SQOrderLineItemAppliedServiceCharge.h"
#import "SQOrderLineItemAppliedTax.h"
#import "SQOrderLineItemModifier.h"
#import "SQOrderLineItemPricingBlocklists.h"
#import "SQOrderQuantityUnit.h"
@protocol SQMoney;
@class SQMoney;
@protocol SQOrderLineItemAppliedDiscount;
@class SQOrderLineItemAppliedDiscount;
@protocol SQOrderLineItemAppliedServiceCharge;
@class SQOrderLineItemAppliedServiceCharge;
@protocol SQOrderLineItemAppliedTax;
@class SQOrderLineItemAppliedTax;
@protocol SQOrderLineItemModifier;
@class SQOrderLineItemModifier;
@protocol SQOrderLineItemPricingBlocklists;
@class SQOrderLineItemPricingBlocklists;
@protocol SQOrderQuantityUnit;
@class SQOrderQuantityUnit;



@protocol SQOrderLineItem
@end

@interface SQOrderLineItem : SQObject

/* A unique ID that identifies the line item only within this order. [optional]
 */
@property(nonatomic) NSString* uid;
/* The name of the line item. [optional]
 */
@property(nonatomic) NSString* name;
/* The quantity purchased, formatted as a decimal number. For example, `\"3\"`.  Line items with a quantity of `\"0\"` are automatically removed when paying for or otherwise completing the order.  Line items with a `quantity_unit` can have non-integer quantities. For example, `\"1.70000\"`. 
 */
@property(nonatomic) NSString* quantity;
/* The unit and precision that this line item's quantity is measured in. [optional]
 */
@property(nonatomic) SQOrderQuantityUnit* quantityUnit;
/* The note of the line item. [optional]
 */
@property(nonatomic) NSString* note;
/* The [CatalogItemVariation](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogItemVariation) ID applied to this line item. [optional]
 */
@property(nonatomic) NSString* catalogObjectId;
/* The version of the catalog object that this line item references. [optional]
 */
@property(nonatomic) NSNumber* catalogVersion;
/* The name of the variation applied to this line item. [optional]
 */
@property(nonatomic) NSString* variationName;
/* The type of line item: an itemized sale, a non-itemized sale (custom amount), or the activation or reloading of a gift card. [optional]
 */
@property(nonatomic) NSString* itemType;
/* Application-defined data attached to this line item. Metadata fields are intended to store descriptive references or associations with an entity in another system or store brief information about the object. Square does not process this field; it only stores and returns it in relevant API calls. Do not use metadata to store any sensitive information (such as personally identifiable information or card details).  Keys written by applications must be 60 characters or less and must be in the character set `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed with a namespace, separated from the key with a ':' character.  Values have a maximum length of 255 characters.  An application can have up to 10 entries per metadata field.  Entries written by applications are private and can only be read or modified by the same application.  For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata). [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* metadata;
/* The [CatalogModifier](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogModifier)s applied to this line item. [optional]
 */
@property(nonatomic) NSArray<SQOrderLineItemModifier>* modifiers;
/* The list of references to taxes applied to this line item. Each `OrderLineItemAppliedTax` has a `tax_uid` that references the `uid` of a top-level `OrderLineItemTax` applied to the line item. On reads, the amount applied is populated.  An `OrderLineItemAppliedTax` is automatically created on every line item for all `ORDER` scoped taxes added to the order. `OrderLineItemAppliedTax` records for `LINE_ITEM` scoped taxes must be added in requests for the tax to apply to any line items.  To change the amount of a tax, modify the referenced top-level tax. [optional]
 */
@property(nonatomic) NSArray<SQOrderLineItemAppliedTax>* appliedTaxes;
/* The list of references to discounts applied to this line item. Each `OrderLineItemAppliedDiscount` has a `discount_uid` that references the `uid` of a top-level `OrderLineItemDiscounts` applied to the line item. On reads, the amount applied is populated.  An `OrderLineItemAppliedDiscount` is automatically created on every line item for all `ORDER` scoped discounts that are added to the order. `OrderLineItemAppliedDiscount` records for `LINE_ITEM` scoped discounts must be added in requests for the discount to apply to any line items.  To change the amount of a discount, modify the referenced top-level discount. [optional]
 */
@property(nonatomic) NSArray<SQOrderLineItemAppliedDiscount>* appliedDiscounts;
/* The list of references to service charges applied to this line item. Each `OrderLineItemAppliedServiceCharge` has a `service_charge_id` that references the `uid` of a top-level `OrderServiceCharge` applied to the line item. On reads, the amount applied is populated.  To change the amount of a service charge, modify the referenced top-level service charge. [optional]
 */
@property(nonatomic) NSArray<SQOrderLineItemAppliedServiceCharge>* appliedServiceCharges;
/* The base price for a single unit of the line item. [optional]
 */
@property(nonatomic) SQMoney* basePriceMoney;
/* The total price of all item variations sold in this line item. The price is calculated as `base_price_money` multiplied by `quantity`. It does not include modifiers. [optional]
 */
@property(nonatomic) SQMoney* variationTotalPriceMoney;
/* The amount of money made in gross sales for this line item. The amount is calculated as the sum of the variation's total price and each modifier's total price. [optional]
 */
@property(nonatomic) SQMoney* grossSalesMoney;
/* The total amount of tax money to collect for the line item. [optional]
 */
@property(nonatomic) SQMoney* totalTaxMoney;
/* The total amount of discount money to collect for the line item. [optional]
 */
@property(nonatomic) SQMoney* totalDiscountMoney;
/* The total amount of money to collect for this line item. [optional]
 */
@property(nonatomic) SQMoney* totalMoney;
/* Describes pricing adjustments that are blocked from automatic application to a line item. For more information, see [Apply Taxes and Discounts](https://developer.squareup.com/docs/orders-api/apply-taxes-and-discounts). [optional]
 */
@property(nonatomic) SQOrderLineItemPricingBlocklists* pricingBlocklists;
/* The total amount of apportioned service charge money to collect for the line item. [optional]
 */
@property(nonatomic) SQMoney* totalServiceChargeMoney;

@end
