#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQOrderReturnDiscount
@end

@interface SQOrderReturnDiscount : SQObject

/* A unique ID that identifies the returned discount only within this order. [optional]
 */
@property(nonatomic) NSString* uid;
/* The discount `uid` from the order that contains the original application of this discount. [optional]
 */
@property(nonatomic) NSString* sourceDiscountUid;
/* The catalog object ID referencing [CatalogDiscount](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogDiscount). [optional]
 */
@property(nonatomic) NSString* catalogObjectId;
/* The version of the catalog object that this discount references. [optional]
 */
@property(nonatomic) NSNumber* catalogVersion;
/* The discount's name. [optional]
 */
@property(nonatomic) NSString* name;
/* The type of the discount. If it is created by the API, it is `FIXED_PERCENTAGE` or `FIXED_AMOUNT`.  Discounts that do not reference a catalog object ID must have a type of `FIXED_PERCENTAGE` or `FIXED_AMOUNT`. [optional]
 */
@property(nonatomic) NSString* type;
/* The percentage of the tax, as a string representation of a decimal number. A value of `\"7.25\"` corresponds to a percentage of 7.25%.  `percentage` is not set for amount-based discounts. [optional]
 */
@property(nonatomic) NSString* percentage;
/* The total declared monetary amount of the discount.  `amount_money` is not set for percentage-based discounts. [optional]
 */
@property(nonatomic) SQMoney* amountMoney;
/* The amount of discount actually applied to this line item. When an amount-based discount is at the order level, this value is different from `amount_money` because the discount is distributed across the line items. [optional]
 */
@property(nonatomic) SQMoney* appliedMoney;
/* Indicates the level at which the `OrderReturnDiscount` applies. For `ORDER` scoped discounts, the server generates references in `applied_discounts` on all `OrderReturnLineItem`s. For `LINE_ITEM` scoped discounts, the discount is only applied to `OrderReturnLineItem`s with references in their `applied_discounts` field. [optional]
 */
@property(nonatomic) NSString* scope;

@end
