#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQOrderUpdated
@end

@interface SQOrderUpdated : SQObject

/* The order's unique ID. [optional]
 */
@property(nonatomic) NSString* orderId;
/* The version number, which is incremented each time an update is committed to the order. Orders that were not created through the API do not include a version number and therefore cannot be updated.  [Read more about working with versions.](https://developer.squareup.com/docs/orders-api/manage-orders/update-orders) [optional]
 */
@property(nonatomic) NSNumber* version;
/* The ID of the seller location that this order is associated with. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The state of the order. [optional]
 */
@property(nonatomic) NSString* state;
/* The timestamp for when the order was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The timestamp for when the order was last updated, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* updatedAt;

@end
