#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQOrderLineItemDiscount
@end

@interface SQOrderLineItemDiscount : SQObject

/* A unique ID that identifies the discount only within this order. [optional]
 */
@property(nonatomic) NSString* uid;
/* The catalog object ID referencing [CatalogDiscount](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogDiscount). [optional]
 */
@property(nonatomic) NSString* catalogObjectId;
/* The version of the catalog object that this discount references. [optional]
 */
@property(nonatomic) NSNumber* catalogVersion;
/* The discount's name. [optional]
 */
@property(nonatomic) NSString* name;
/* The type of the discount.  Discounts that do not reference a catalog object ID must have a type of `FIXED_PERCENTAGE` or `FIXED_AMOUNT`. [optional]
 */
@property(nonatomic) NSString* type;
/* The percentage of the discount, as a string representation of a decimal number. A value of `7.25` corresponds to a percentage of 7.25%.  `percentage` is not set for amount-based discounts. [optional]
 */
@property(nonatomic) NSString* percentage;
/* The total declared monetary amount of the discount.  `amount_money` is not set for percentage-based discounts. [optional]
 */
@property(nonatomic) SQMoney* amountMoney;
/* The amount of discount actually applied to the line item.  The amount represents the amount of money applied as a line-item scoped discount. When an amount-based discount is scoped to the entire order, the value of `applied_money` is different than `amount_money` because the total amount of the discount is distributed across all line items. [optional]
 */
@property(nonatomic) SQMoney* appliedMoney;
/* Application-defined data attached to this discount. Metadata fields are intended to store descriptive references or associations with an entity in another system or store brief information about the object. Square does not process this field; it only stores and returns it in relevant API calls. Do not use metadata to store any sensitive information (such as personally identifiable information or card details).  Keys written by applications must be 60 characters or less and must be in the character set `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed with a namespace, separated from the key with a ':' character.  Values have a maximum length of 255 characters.  An application can have up to 10 entries per metadata field.  Entries written by applications are private and can only be read or modified by the same application.  For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata). [optional]
 */
@property(nonatomic) NSDictionary<NSString*, NSString*>* metadata;
/* Indicates the level at which the discount applies. For `ORDER` scoped discounts, Square generates references in `applied_discounts` on all order line items that do not have them. For `LINE_ITEM` scoped discounts, the discount only applies to line items with a discount reference in their `applied_discounts` field.  This field is immutable. To change the scope of a discount, you must delete the discount and re-add it as a new discount. [optional]
 */
@property(nonatomic) NSString* scope;
/* The reward IDs corresponding to this discount. The application and specification of discounts that have `reward_ids` are completely controlled by the backing criteria corresponding to the reward tiers of the rewards that are added to the order through the Loyalty API. To manually unapply discounts that are the result of added rewards, the rewards must be removed from the order through the Loyalty API. [optional]
 */
@property(nonatomic) NSArray<NSString*>* rewardIds;
/* The object ID of a [pricing rule](https://developer.squareup.com/reference/square_2023-10-18/objects/CatalogPricingRule) to be applied automatically to this discount. The specification and application of the discounts, to which a `pricing_rule_id` is assigned, are completely controlled by the corresponding pricing rule. [optional]
 */
@property(nonatomic) NSString* pricingRuleId;

@end
