#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQOrderReward
@end

@interface SQOrderReward : SQObject

/* The identifier of the reward. 
 */
@property(nonatomic) NSString* _id;
/* The identifier of the reward tier corresponding to this reward. 
 */
@property(nonatomic) NSString* rewardTierId;

@end
