#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQOrderEntry
@end

@interface SQOrderEntry : SQObject

/* The ID of the order. [optional]
 */
@property(nonatomic) NSString* orderId;
/* The version number, which is incremented each time an update is committed to the order. Orders that were not created through the API do not include a version number and therefore cannot be updated.  [Read more about working with versions.](https://developer.squareup.com/docs/orders-api/manage-orders/update-orders) [optional]
 */
@property(nonatomic) NSNumber* version;
/* The location ID the order belongs to. [optional]
 */
@property(nonatomic) NSString* locationId;

@end
