#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQSubscription.h"
#import "SQSubscriptionAction.h"
@protocol SQError;
@class SQError;
@protocol SQSubscription;
@class SQSubscription;
@protocol SQSubscriptionAction;
@class SQSubscriptionAction;



@protocol SQPauseSubscriptionResponse
@end

@interface SQPauseSubscriptionResponse : SQObject

/* Errors encountered during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The subscription to be paused by the scheduled `PAUSE` action. [optional]
 */
@property(nonatomic) SQSubscription* subscription;
/* The list of a `PAUSE` action and a possible `RESUME` action created by the request. [optional]
 */
@property(nonatomic) NSArray<SQSubscriptionAction>* actions;

@end
