#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQPayoutFee
@end

@interface SQPayoutFee : SQObject

/* The money amount of the payout fee. [optional]
 */
@property(nonatomic) SQMoney* amountMoney;
/* The timestamp of when the fee takes effect, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* effectiveAt;
/* The type of fee assessed as part of the payout. [optional]
 */
@property(nonatomic) NSString* type;

@end
