#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQPayOrderRequest
@end

@interface SQPayOrderRequest : SQObject

/* A value you specify that uniquely identifies this request among requests you have sent. If you are unsure whether a particular payment request was completed successfully, you can reattempt it with the same idempotency key without worrying about duplicate payments.  For more information, see [Idempotency](https://developer.squareup.com/docs/working-with-apis/idempotency). 
 */
@property(nonatomic) NSString* idempotencyKey;
/* The version of the order being paid. If not supplied, the latest version will be paid. [optional]
 */
@property(nonatomic) NSNumber* orderVersion;
/* The IDs of the [payments](https://developer.squareup.com/reference/square_2023-10-18/objects/Payment) to collect. The payment total must match the order total. [optional]
 */
@property(nonatomic) NSArray<NSString*>* paymentIds;

@end
