#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
#import "SQPaymentBalanceActivityAppFeeRefundDetail.h"
#import "SQPaymentBalanceActivityAppFeeRevenueDetail.h"
#import "SQPaymentBalanceActivityAutomaticSavingsDetail.h"
#import "SQPaymentBalanceActivityAutomaticSavingsReversedDetail.h"
#import "SQPaymentBalanceActivityChargeDetail.h"
#import "SQPaymentBalanceActivityDepositFeeDetail.h"
#import "SQPaymentBalanceActivityDisputeDetail.h"
#import "SQPaymentBalanceActivityFeeDetail.h"
#import "SQPaymentBalanceActivityFreeProcessingDetail.h"
#import "SQPaymentBalanceActivityHoldAdjustmentDetail.h"
#import "SQPaymentBalanceActivityOpenDisputeDetail.h"
#import "SQPaymentBalanceActivityOtherAdjustmentDetail.h"
#import "SQPaymentBalanceActivityOtherDetail.h"
#import "SQPaymentBalanceActivityRefundDetail.h"
#import "SQPaymentBalanceActivityReleaseAdjustmentDetail.h"
#import "SQPaymentBalanceActivityReserveHoldDetail.h"
#import "SQPaymentBalanceActivityReserveReleaseDetail.h"
#import "SQPaymentBalanceActivitySquareCapitalPaymentDetail.h"
#import "SQPaymentBalanceActivitySquareCapitalReversedPaymentDetail.h"
#import "SQPaymentBalanceActivityTaxOnFeeDetail.h"
#import "SQPaymentBalanceActivityThirdPartyFeeDetail.h"
#import "SQPaymentBalanceActivityThirdPartyFeeRefundDetail.h"
@protocol SQMoney;
@class SQMoney;
@protocol SQPaymentBalanceActivityAppFeeRefundDetail;
@class SQPaymentBalanceActivityAppFeeRefundDetail;
@protocol SQPaymentBalanceActivityAppFeeRevenueDetail;
@class SQPaymentBalanceActivityAppFeeRevenueDetail;
@protocol SQPaymentBalanceActivityAutomaticSavingsDetail;
@class SQPaymentBalanceActivityAutomaticSavingsDetail;
@protocol SQPaymentBalanceActivityAutomaticSavingsReversedDetail;
@class SQPaymentBalanceActivityAutomaticSavingsReversedDetail;
@protocol SQPaymentBalanceActivityChargeDetail;
@class SQPaymentBalanceActivityChargeDetail;
@protocol SQPaymentBalanceActivityDepositFeeDetail;
@class SQPaymentBalanceActivityDepositFeeDetail;
@protocol SQPaymentBalanceActivityDisputeDetail;
@class SQPaymentBalanceActivityDisputeDetail;
@protocol SQPaymentBalanceActivityFeeDetail;
@class SQPaymentBalanceActivityFeeDetail;
@protocol SQPaymentBalanceActivityFreeProcessingDetail;
@class SQPaymentBalanceActivityFreeProcessingDetail;
@protocol SQPaymentBalanceActivityHoldAdjustmentDetail;
@class SQPaymentBalanceActivityHoldAdjustmentDetail;
@protocol SQPaymentBalanceActivityOpenDisputeDetail;
@class SQPaymentBalanceActivityOpenDisputeDetail;
@protocol SQPaymentBalanceActivityOtherAdjustmentDetail;
@class SQPaymentBalanceActivityOtherAdjustmentDetail;
@protocol SQPaymentBalanceActivityOtherDetail;
@class SQPaymentBalanceActivityOtherDetail;
@protocol SQPaymentBalanceActivityRefundDetail;
@class SQPaymentBalanceActivityRefundDetail;
@protocol SQPaymentBalanceActivityReleaseAdjustmentDetail;
@class SQPaymentBalanceActivityReleaseAdjustmentDetail;
@protocol SQPaymentBalanceActivityReserveHoldDetail;
@class SQPaymentBalanceActivityReserveHoldDetail;
@protocol SQPaymentBalanceActivityReserveReleaseDetail;
@class SQPaymentBalanceActivityReserveReleaseDetail;
@protocol SQPaymentBalanceActivitySquareCapitalPaymentDetail;
@class SQPaymentBalanceActivitySquareCapitalPaymentDetail;
@protocol SQPaymentBalanceActivitySquareCapitalReversedPaymentDetail;
@class SQPaymentBalanceActivitySquareCapitalReversedPaymentDetail;
@protocol SQPaymentBalanceActivityTaxOnFeeDetail;
@class SQPaymentBalanceActivityTaxOnFeeDetail;
@protocol SQPaymentBalanceActivityThirdPartyFeeDetail;
@class SQPaymentBalanceActivityThirdPartyFeeDetail;
@protocol SQPaymentBalanceActivityThirdPartyFeeRefundDetail;
@class SQPaymentBalanceActivityThirdPartyFeeRefundDetail;



@protocol SQPayoutEntry
@end

@interface SQPayoutEntry : SQObject

/* A unique ID for the payout entry. 
 */
@property(nonatomic) NSString* _id;
/* The ID of the payout entries’ associated payout. 
 */
@property(nonatomic) NSString* payoutId;
/* The timestamp of when the payout entry affected the balance, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* effectiveAt;
/* The type of activity associated with this payout entry. [optional]
 */
@property(nonatomic) NSString* type;
/* The amount of money involved in this payout entry. [optional]
 */
@property(nonatomic) SQMoney* grossAmountMoney;
/* The amount of Square fees associated with this payout entry. [optional]
 */
@property(nonatomic) SQMoney* feeAmountMoney;
/* The net proceeds from this transaction after any fees. [optional]
 */
@property(nonatomic) SQMoney* netAmountMoney;
/* Details of any developer app fee revenue generated on a payment. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityAppFeeRevenueDetail* typeAppFeeRevenueDetails;
/* Details of a refund for an app fee on a payment. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityAppFeeRefundDetail* typeAppFeeRefundDetails;
/* Details of any automatic transfer from the payment processing balance to the Square Savings account. These are, generally, proportional to the merchant's sales. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityAutomaticSavingsDetail* typeAutomaticSavingsDetails;
/* Details of any automatic transfer from the Square Savings account back to the processing balance. These are, generally, proportional to the merchant's refunds. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityAutomaticSavingsReversedDetail* typeAutomaticSavingsReversedDetails;
/* Details of credit card payment captures. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityChargeDetail* typeChargeDetails;
/* Details of any fees involved with deposits such as for instant deposits. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityDepositFeeDetail* typeDepositFeeDetails;
/* Details of any balance change due to a dispute event. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityDisputeDetail* typeDisputeDetails;
/* Details of adjustments due to the Square processing fee. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityFeeDetail* typeFeeDetails;
/* Square offers Free Payments Processing for a variety of business scenarios including seller referral or when Square wants to apologize for a bug, customer service, repricing complication, and so on. This entry represents details of any credit to the merchant for the purposes of Free Processing. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityFreeProcessingDetail* typeFreeProcessingDetails;
/* Details of any adjustment made by Square related to the holding or releasing of a payment. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityHoldAdjustmentDetail* typeHoldAdjustmentDetails;
/* Details of any open disputes. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityOpenDisputeDetail* typeOpenDisputeDetails;
/* Details of any other type that does not belong in the rest of the types. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityOtherDetail* typeOtherDetails;
/* Details of any other type of adjustments that don't fall under existing types. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityOtherAdjustmentDetail* typeOtherAdjustmentDetails;
/* Details of a refund for an existing card payment. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityRefundDetail* typeRefundDetails;
/* Details of fees released for adjustments. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityReleaseAdjustmentDetail* typeReleaseAdjustmentDetails;
/* Details of fees paid for funding risk reserve. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityReserveHoldDetail* typeReserveHoldDetails;
/* Details of fees released from risk reserve. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityReserveReleaseDetail* typeReserveReleaseDetails;
/* Details of capital merchant cash advance (MCA) assessments. These are, generally, proportional to the merchant's sales but may be issued for other reasons related to the MCA. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivitySquareCapitalPaymentDetail* typeSquareCapitalPaymentDetails;
/* Details of capital merchant cash advance (MCA) assessment refunds. These are, generally, proportional to the merchant's refunds but may be issued for other reasons related to the MCA. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivitySquareCapitalReversedPaymentDetail* typeSquareCapitalReversedPaymentDetails;
/* Details of tax paid on fee amounts. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityTaxOnFeeDetail* typeTaxOnFeeDetails;
/* Details of fees collected by a 3rd party platform. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityThirdPartyFeeDetail* typeThirdPartyFeeDetails;
/* Details of refunded fees from a 3rd party platform. [optional]
 */
@property(nonatomic) SQPaymentBalanceActivityThirdPartyFeeRefundDetail* typeThirdPartyFeeRefundDetails;

@end
