#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQPauseSubscriptionRequest
@end

@interface SQPauseSubscriptionRequest : SQObject

/* The `YYYY-MM-DD`-formatted date when the scheduled `PAUSE` action takes place on the subscription.  When this date is unspecified or falls within the current billing cycle, the subscription is paused on the starting date of the next billing cycle. [optional]
 */
@property(nonatomic) NSString* pauseEffectiveDate;
/* The number of billing cycles the subscription will be paused before it is reactivated.   When this is set, a `RESUME` action is also scheduled to take place on the subscription at  the end of the specified pause cycle duration. In this case, neither `resume_effective_date`  nor `resume_change_timing` may be specified. [optional]
 */
@property(nonatomic) NSNumber* pauseCycleDuration;
/* The date when the subscription is reactivated by a scheduled `RESUME` action.  This date must be at least one billing cycle ahead of `pause_effective_date`. [optional]
 */
@property(nonatomic) NSString* resumeEffectiveDate;
/* The timing whether the subscription is reactivated immediately or at the end of the billing cycle, relative to  `resume_effective_date`. [optional]
 */
@property(nonatomic) NSString* resumeChangeTiming;
/* The user-provided reason to pause the subscription. [optional]
 */
@property(nonatomic) NSString* pauseReason;

@end
