#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQPaginationCursor
@end

@interface SQPaginationCursor : SQObject

/* The ID of the last resource in the current page. The page can be in an ascending or descending order [optional]
 */
@property(nonatomic) NSString* orderValue;

@end
