#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQProcessingFee
@end

@interface SQProcessingFee : SQObject

/* The timestamp of when the fee takes effect, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* effectiveAt;
/* The type of fee assessed or adjusted. The fee type can be `INITIAL` or `ADJUSTMENT`. [optional]
 */
@property(nonatomic) NSString* type;
/* The fee amount, which might be negative, that is assessed or adjusted by Square.  Positive values represent funds being assessed, while negative values represent funds being returned. [optional]
 */
@property(nonatomic) SQMoney* amountMoney;

@end
