#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQQrCodeOptions
@end

@interface SQQrCodeOptions : SQObject

/* The title text to display in the QR code flow on the Terminal. 
 */
@property(nonatomic) NSString* title;
/* The body text to display in the QR code flow on the Terminal. 
 */
@property(nonatomic) NSString* body;
/* The text representation of the data to show in the QR code as UTF8-encoded data. 
 */
@property(nonatomic) NSString* barcodeContents;

@end
