#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQRange
@end

@interface SQRange : SQObject

/* The lower bound of the number range. At least one of `min` or `max` must be specified. If unspecified, the results will have no minimum value. [optional]
 */
@property(nonatomic) NSString* min;
/* The upper bound of the number range. At least one of `min` or `max` must be specified. If unspecified, the results will have no maximum value. [optional]
 */
@property(nonatomic) NSString* max;

@end
