#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQResumeSubscriptionRequest
@end

@interface SQResumeSubscriptionRequest : SQObject

/* The `YYYY-MM-DD`-formatted date when the subscription reactivated. [optional]
 */
@property(nonatomic) NSString* resumeEffectiveDate;
/* The timing to resume a subscription, relative to the specified `resume_effective_date` attribute value. [optional]
 */
@property(nonatomic) NSString* resumeChangeTiming;

@end
