#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQAdditionalRecipient.h"
#import "SQMoney.h"
@protocol SQAdditionalRecipient;
@class SQAdditionalRecipient;
@protocol SQMoney;
@class SQMoney;



@protocol SQRefund
@end

@interface SQRefund : SQObject

/* The refund's unique ID. 
 */
@property(nonatomic) NSString* _id;
/* The ID of the refund's associated location. 
 */
@property(nonatomic) NSString* locationId;
/* The ID of the transaction that the refunded tender is part of. [optional]
 */
@property(nonatomic) NSString* transactionId;
/* The ID of the refunded tender. 
 */
@property(nonatomic) NSString* tenderId;
/* The timestamp for when the refund was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The reason for the refund being issued. 
 */
@property(nonatomic) NSString* reason;
/* The amount of money refunded to the buyer. 
 */
@property(nonatomic) SQMoney* amountMoney;
/* The current status of the refund (`PENDING`, `APPROVED`, `REJECTED`, or `FAILED`). 
 */
@property(nonatomic) NSString* status;
/* The amount of Square processing fee money refunded to the *merchant*. [optional]
 */
@property(nonatomic) SQMoney* processingFeeMoney;
/* Additional recipients (other than the merchant) receiving a portion of this refund. For example, fees assessed on a refund of a purchase by a third party integration. [optional]
 */
@property(nonatomic) NSArray<SQAdditionalRecipient>* additionalRecipients;

@end
