#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQRetrieveInventoryCountRequest
@end

@interface SQRetrieveInventoryCountRequest : SQObject

/* The [Location](https://developer.squareup.com/reference/square_2023-10-18/objects/Location) IDs to look up as a comma-separated list. An empty list queries all locations. [optional]
 */
@property(nonatomic) NSString* locationIds;
/* A pagination cursor returned by a previous call to this endpoint. Provide this to retrieve the next set of results for the original query.  See the [Pagination](https://developer.squareup.com/docs/working-with-apis/pagination) guide for more information. [optional]
 */
@property(nonatomic) NSString* cursor;

@end
