#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQRegisterDomainRequest
@end

@interface SQRegisterDomainRequest : SQObject

/* A domain name as described in RFC-1034 that will be registered with ApplePay. 
 */
@property(nonatomic) NSString* domainName;

@end
