#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQTerminalRefundQuery.h"
@protocol SQTerminalRefundQuery;
@class SQTerminalRefundQuery;



@protocol SQSearchTerminalRefundsRequest
@end

@interface SQSearchTerminalRefundsRequest : SQObject

/* Queries the Terminal refunds based on given conditions and the sort order. Calling `SearchTerminalRefunds` without an explicit query parameter returns all available refunds with the default sort order. [optional]
 */
@property(nonatomic) SQTerminalRefundQuery* query;
/* A pagination cursor returned by a previous call to this endpoint. Provide this cursor to retrieve the next set of results for the original query. [optional]
 */
@property(nonatomic) NSString* cursor;
/* Limits the number of results returned for a single request. [optional]
 */
@property(nonatomic) NSNumber* limit;

@end
