#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQAvailability.h"
#import "SQError.h"
@protocol SQAvailability;
@class SQAvailability;
@protocol SQError;
@class SQError;



@protocol SQSearchAvailabilityResponse
@end

@interface SQSearchAvailabilityResponse : SQObject

/* List of appointment slots available for booking. [optional]
 */
@property(nonatomic) NSArray<SQAvailability>* availabilities;
/* Errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;

@end
