#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQSearchOrdersSort
@end

@interface SQSearchOrdersSort : SQObject

/* The field to sort by.  __Important:__ When using a [DateTimeFilter](https://developer.squareup.com/reference/square_2023-10-18/objects/SearchOrdersFilter), `sort_field` must match the timestamp field that the `DateTimeFilter` uses to filter. For example, if you set your `sort_field` to `CLOSED_AT` and you use a `DateTimeFilter`, your `DateTimeFilter` must filter for orders by their `CLOSED_AT` date. If this field does not match the timestamp field in `DateTimeFilter`, `SearchOrders` returns an error.  Default: `CREATED_AT`. 
 */
@property(nonatomic) NSString* sortField;
/* The chronological order in which results are returned. Defaults to `DESC`. [optional]
 */
@property(nonatomic) NSString* sortOrder;

@end
