#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQCustomAttributeFilter.h"
@protocol SQCustomAttributeFilter;
@class SQCustomAttributeFilter;



@protocol SQSearchCatalogItemsRequest
@end

@interface SQSearchCatalogItemsRequest : SQObject

/* The text filter expression to return items or item variations containing specified text in the `name`, `description`, or `abbreviation` attribute value of an item, or in the `name`, `sku`, or `upc` attribute value of an item variation. [optional]
 */
@property(nonatomic) NSString* textFilter;
/* The category id query expression to return items containing the specified category IDs. [optional]
 */
@property(nonatomic) NSArray<NSString*>* categoryIds;
/* The stock-level query expression to return item variations with the specified stock levels. [optional]
 */
@property(nonatomic) NSArray<NSString*>* stockLevels;
/* The enabled-location query expression to return items and item variations having specified enabled locations. [optional]
 */
@property(nonatomic) NSArray<NSString*>* enabledLocationIds;
/* The pagination token, returned in the previous response, used to fetch the next batch of pending results. [optional]
 */
@property(nonatomic) NSString* cursor;
/* The maximum number of results to return per page. The default value is 100. [optional]
 */
@property(nonatomic) NSNumber* limit;
/* The order to sort the results by item names. The default sort order is ascending (`ASC`). [optional]
 */
@property(nonatomic) NSString* sortOrder;
/* The product types query expression to return items or item variations having the specified product types. [optional]
 */
@property(nonatomic) NSArray<NSString*>* productTypes;
/* The customer-attribute filter to return items or item variations matching the specified custom attribute expressions. A maximum number of 10 custom attribute expressions are supported in a single call to the [SearchCatalogItems](https://developer.squareup.com/reference/square_2023-10-18/catalog-api/search-catalog-items) endpoint. [optional]
 */
@property(nonatomic) NSArray<SQCustomAttributeFilter>* customAttributeFilters;
/* The query filter to return not archived (`ARCHIVED_STATE_NOT_ARCHIVED`), archived (`ARCHIVED_STATE_ARCHIVED`), or either type (`ARCHIVED_STATE_ALL`) of items. [optional]
 */
@property(nonatomic) NSString* archivedState;

@end
