#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQSearchOrdersFulfillmentFilter
@end

@interface SQSearchOrdersFulfillmentFilter : SQObject

/* A list of [fulfillment types](https://developer.squareup.com/reference/square_2023-10-18/enums/FulfillmentType) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment types listed in this field. [optional]
 */
@property(nonatomic) NSArray<NSString*>* fulfillmentTypes;
/* A list of [fulfillment states](https://developer.squareup.com/reference/square_2023-10-18/enums/FulfillmentState) to filter for. The list returns orders if any of its fulfillments match any of the fulfillment states listed in this field. [optional]
 */
@property(nonatomic) NSArray<NSString*>* fulfillmentStates;

@end
