#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQSearchLoyaltyRewardsRequestLoyaltyRewardQuery
@end

@interface SQSearchLoyaltyRewardsRequestLoyaltyRewardQuery : SQObject

/* The ID of the [loyalty account](https://developer.squareup.com/reference/square_2023-10-18/objects/LoyaltyAccount) to which the loyalty reward belongs. 
 */
@property(nonatomic) NSString* loyaltyAccountId;
/* The status of the loyalty reward. [optional]
 */
@property(nonatomic) NSString* status;

@end
