#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQSearchTeamMembersQuery.h"
@protocol SQSearchTeamMembersQuery;
@class SQSearchTeamMembersQuery;



@protocol SQSearchTeamMembersRequest
@end

@interface SQSearchTeamMembersRequest : SQObject

/* The query parameters. [optional]
 */
@property(nonatomic) SQSearchTeamMembersQuery* query;
/* The maximum number of `TeamMember` objects in a page (100 by default). [optional]
 */
@property(nonatomic) NSNumber* limit;
/* The opaque cursor for fetching the next page. For more information, see [pagination](https://developer.squareup.com/docs/working-with-apis/pagination). [optional]
 */
@property(nonatomic) NSString* cursor;

@end
