#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQSearchOrdersCustomerFilter
@end

@interface SQSearchOrdersCustomerFilter : SQObject

/* A list of customer IDs to filter by.  Max: 10 customer IDs. [optional]
 */
@property(nonatomic) NSArray<NSString*>* customerIds;

@end
