#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQLoyaltyAccountMapping.h"
@protocol SQLoyaltyAccountMapping;
@class SQLoyaltyAccountMapping;



@protocol SQSearchLoyaltyAccountsRequestLoyaltyAccountQuery
@end

@interface SQSearchLoyaltyAccountsRequestLoyaltyAccountQuery : SQObject

/* The set of mappings to use in the loyalty account search.    This cannot be combined with `customer_ids`.    Max: 30 mappings [optional]
 */
@property(nonatomic) NSArray<SQLoyaltyAccountMapping>* mappings;
/* The set of customer IDs to use in the loyalty account search.    This cannot be combined with `mappings`.    Max: 30 customer IDs [optional]
 */
@property(nonatomic) NSArray<NSString*>* customerIds;

@end
