#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQSelectOption.h"
@protocol SQSelectOption;
@class SQSelectOption;



@protocol SQSelectOptions
@end

@interface SQSelectOptions : SQObject

/* The title text to display in the select flow on the Terminal. 
 */
@property(nonatomic) NSString* title;
/* The body text to display in the select flow on the Terminal. 
 */
@property(nonatomic) NSString* body;
/* Represents the buttons/options that should be displayed in the select flow on the Terminal. 
 */
@property(nonatomic) NSArray<SQSelectOption>* options;
/* The buyer’s selected option. [optional]
 */
@property(nonatomic) SQSelectOption* selectedOption;

@end
