#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQInvoiceQuery.h"
@protocol SQInvoiceQuery;
@class SQInvoiceQuery;



@protocol SQSearchInvoicesRequest
@end

@interface SQSearchInvoicesRequest : SQObject

/* Describes the query criteria for searching invoices. 
 */
@property(nonatomic) SQInvoiceQuery* query;
/* The maximum number of invoices to return (200 is the maximum `limit`).  If not provided, the server uses a default limit of 100 invoices. [optional]
 */
@property(nonatomic) NSNumber* limit;
/* A pagination cursor returned by a previous call to this endpoint.  Provide this cursor to retrieve the next set of results for your original query.  For more information, see [Pagination](https://developer.squareup.com/docs/build-basics/common-api-patterns/pagination). [optional]
 */
@property(nonatomic) NSString* cursor;

@end
