#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQMoney.h"
@protocol SQMoney;
@class SQMoney;



@protocol SQShiftWage
@end

@interface SQShiftWage : SQObject

/* The name of the job performed during this shift. [optional]
 */
@property(nonatomic) NSString* title;
/* Can be a custom-set hourly wage or the calculated effective hourly wage based on the annual wage and hours worked per week. [optional]
 */
@property(nonatomic) SQMoney* hourlyRate;
/* The id of the job performed during this shift. Square labor-reporting UIs might group shifts together by id. This cannot be used to retrieve the job. [optional]
 */
@property(nonatomic) NSString* jobId;

@end
