#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQShiftFilter.h"
#import "SQShiftSort.h"
@protocol SQShiftFilter;
@class SQShiftFilter;
@protocol SQShiftSort;
@class SQShiftSort;



@protocol SQShiftQuery
@end

@interface SQShiftQuery : SQObject

/* Query filter options. [optional]
 */
@property(nonatomic) SQShiftFilter* filter;
/* Sort order details. [optional]
 */
@property(nonatomic) SQShiftSort* sort;

@end
