#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQSignatureImage.h"
@protocol SQSignatureImage;
@class SQSignatureImage;



@protocol SQSignatureOptions
@end

@interface SQSignatureOptions : SQObject

/* The title text to display in the signature capture flow on the Terminal. 
 */
@property(nonatomic) NSString* title;
/* The body text to display in the signature capture flow on the Terminal. 
 */
@property(nonatomic) NSString* body;
/* An image representation of the collected signature. [optional]
 */
@property(nonatomic) NSArray<SQSignatureImage>* signature;

@end
