#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQSite
@end

@interface SQSite : SQObject

/* The Square-assigned ID of the site. [optional]
 */
@property(nonatomic) NSString* _id;
/* The title of the site. [optional]
 */
@property(nonatomic) NSString* siteTitle;
/* The domain of the site (without the protocol). For example, `mysite1.square.site`. [optional]
 */
@property(nonatomic) NSString* domain;
/* Indicates whether the site is published. [optional]
 */
@property(nonatomic) NSNumber* isPublished;
/* The timestamp of when the site was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The timestamp of when the site was last updated, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* updatedAt;

@end
