#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQConfirmationOptions.h"
#import "SQDataCollectionOptions.h"
#import "SQDeviceMetadata.h"
#import "SQQrCodeOptions.h"
#import "SQReceiptOptions.h"
#import "SQSaveCardOptions.h"
#import "SQSelectOptions.h"
#import "SQSignatureOptions.h"
@protocol SQConfirmationOptions;
@class SQConfirmationOptions;
@protocol SQDataCollectionOptions;
@class SQDataCollectionOptions;
@protocol SQDeviceMetadata;
@class SQDeviceMetadata;
@protocol SQQrCodeOptions;
@class SQQrCodeOptions;
@protocol SQReceiptOptions;
@class SQReceiptOptions;
@protocol SQSaveCardOptions;
@class SQSaveCardOptions;
@protocol SQSelectOptions;
@class SQSelectOptions;
@protocol SQSignatureOptions;
@class SQSignatureOptions;



@protocol SQTerminalAction
@end

@interface SQTerminalAction : SQObject

/* A unique ID for this `TerminalAction`. [optional]
 */
@property(nonatomic) NSString* _id;
/* The unique Id of the device intended for this `TerminalAction`. The Id can be retrieved from /v2/devices api. [optional]
 */
@property(nonatomic) NSString* deviceId;
/* The duration as an RFC 3339 duration, after which the action will be automatically canceled. TerminalActions that are `PENDING` will be automatically `CANCELED` and have a cancellation reason of `TIMED_OUT`  Default: 5 minutes from creation  Maximum: 5 minutes [optional]
 */
@property(nonatomic) NSString* deadlineDuration;
/* The status of the `TerminalAction`. Options: `PENDING`, `IN_PROGRESS`, `CANCEL_REQUESTED`, `CANCELED`, `COMPLETED` [optional]
 */
@property(nonatomic) NSString* status;
/* The reason why `TerminalAction` is canceled. Present if the status is `CANCELED`. [optional]
 */
@property(nonatomic) NSString* cancelReason;
/* The time when the `TerminalAction` was created as an RFC 3339 timestamp. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The time when the `TerminalAction` was last updated as an RFC 3339 timestamp. [optional]
 */
@property(nonatomic) NSString* updatedAt;
/* The ID of the application that created the action. [optional]
 */
@property(nonatomic) NSString* appId;
/* The location id the action is attached to, if a link can be made. [optional]
 */
@property(nonatomic) NSString* locationId;
/* Represents the type of the action. [optional]
 */
@property(nonatomic) NSString* type;
/* Describes configuration for the QR code action. Requires `QR_CODE` type. [optional]
 */
@property(nonatomic) SQQrCodeOptions* qrCodeOptions;
/* Describes configuration for the save-card action. Requires `SAVE_CARD` type. [optional]
 */
@property(nonatomic) SQSaveCardOptions* saveCardOptions;
/* Describes configuration for the signature capture action. Requires `SIGNATURE` type. [optional]
 */
@property(nonatomic) SQSignatureOptions* signatureOptions;
/* Describes configuration for the confirmation action. Requires `CONFIRMATION` type. [optional]
 */
@property(nonatomic) SQConfirmationOptions* confirmationOptions;
/* Describes configuration for the receipt action. Requires `RECEIPT` type. [optional]
 */
@property(nonatomic) SQReceiptOptions* receiptOptions;
/* Describes configuration for the data collection action. Requires `DATA_COLLECTION` type. [optional]
 */
@property(nonatomic) SQDataCollectionOptions* dataCollectionOptions;
/* Describes configuration for the select action. Requires `SELECT` type. [optional]
 */
@property(nonatomic) SQSelectOptions* selectOptions;
/* Details about the Terminal that received the action request (such as battery level, operating system version, and network connection settings).  Only available for `PING` action type. [optional]
 */
@property(nonatomic) SQDeviceMetadata* deviceMetadata;
/* Indicates the action will be linked to another action and requires a waiting dialog to be displayed instead of returning to the idle screen on completion of the action.  Only supported on SIGNATURE, CONFIRMATION, DATA_COLLECTION, and SELECT types. [optional]
 */
@property(nonatomic) NSNumber* awaitNextAction;
/* The timeout duration of the waiting dialog as an RFC 3339 duration, after which the waiting dialog will no longer be displayed and the Terminal will return to the idle screen.  Default: 5 minutes from when the waiting dialog is displayed  Maximum: 5 minutes [optional]
 */
@property(nonatomic) NSString* awaitNextActionDuration;

@end
