#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQTimeRange.h"
@protocol SQTimeRange;
@class SQTimeRange;



@protocol SQTerminalCheckoutQueryFilter
@end

@interface SQTerminalCheckoutQueryFilter : SQObject

/* The `TerminalCheckout` objects associated with a specific device. If no device is specified, then all `TerminalCheckout` objects for the merchant are displayed. [optional]
 */
@property(nonatomic) NSString* deviceId;
/* The time range for the beginning of the reporting period, which is inclusive. Default value: The current time minus one day. Note that `TerminalCheckout`s are available for 30 days after creation. [optional]
 */
@property(nonatomic) SQTimeRange* createdAt;
/* Filtered results with the desired status of the `TerminalCheckout`. Options: `PENDING`, `IN_PROGRESS`, `CANCEL_REQUESTED`, `CANCELED`, `COMPLETED` [optional]
 */
@property(nonatomic) NSString* status;

@end
