#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQTerminalCheckoutQuerySort
@end

@interface SQTerminalCheckoutQuerySort : SQObject

/* The order in which results are listed. Default: `DESC` [optional]
 */
@property(nonatomic) NSString* sortOrder;

@end
