#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQAddress.h"
#import "SQRefund.h"
#import "SQTender.h"
@protocol SQAddress;
@class SQAddress;
@protocol SQRefund;
@class SQRefund;
@protocol SQTender;
@class SQTender;



@protocol SQTransaction
@end

@interface SQTransaction : SQObject

/* The transaction's unique ID, issued by Square payments servers. [optional]
 */
@property(nonatomic) NSString* _id;
/* The ID of the transaction's associated location. [optional]
 */
@property(nonatomic) NSString* locationId;
/* The timestamp for when the transaction was created, in RFC 3339 format. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The tenders used to pay in the transaction. [optional]
 */
@property(nonatomic) NSArray<SQTender>* tenders;
/* Refunds that have been applied to any tender in the transaction. [optional]
 */
@property(nonatomic) NSArray<SQRefund>* refunds;
/* If the transaction was created with the [Charge](https://developer.squareup.com/reference/square_2023-10-18/transactions-api/charge) endpoint, this value is the same as the value provided for the `reference_id` parameter in the request to that endpoint. Otherwise, it is not set. [optional]
 */
@property(nonatomic) NSString* referenceId;
/* The Square product that processed the transaction. [optional]
 */
@property(nonatomic) NSString* product;
/* If the transaction was created in the Square Point of Sale app, this value is the ID generated for the transaction by Square Point of Sale.  This ID has no relationship to the transaction's canonical `id`, which is generated by Square's backend servers. This value is generated for bookkeeping purposes, in case the transaction cannot immediately be completed (for example, if the transaction is processed in offline mode).  It is not currently possible with the Connect API to perform a transaction lookup by this value. [optional]
 */
@property(nonatomic) NSString* clientId;
/* The shipping address provided in the request, if any. [optional]
 */
@property(nonatomic) SQAddress* shippingAddress;
/* The order_id is an identifier for the order associated with this transaction, if any. [optional]
 */
@property(nonatomic) NSString* orderId;

@end
