#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
@protocol SQError;
@class SQError;



@protocol SQUpdateWebhookSubscriptionSignatureKeyResponse
@end

@interface SQUpdateWebhookSubscriptionSignatureKeyResponse : SQObject

/* Information on errors encountered during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The new Square-generated signature key used to validate the origin of the webhook event. [optional]
 */
@property(nonatomic) NSString* signatureKey;

@end
