#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQSubscription.h"
@protocol SQSubscription;
@class SQSubscription;



@protocol SQUpdateSubscriptionRequest
@end

@interface SQUpdateSubscriptionRequest : SQObject

/* The subscription object containing the current version, and fields to update. Unset fields will be left at their current server values, and JSON `null` values will be treated as a request to clear the relevant data. [optional]
 */
@property(nonatomic) SQSubscription* subscription;

@end
