#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQUpdateItemTaxesRequest
@end

@interface SQUpdateItemTaxesRequest : SQObject

/* IDs for the CatalogItems associated with the CatalogTax objects being updated. No more than 1,000 IDs may be provided. 
 */
@property(nonatomic) NSArray<NSString*>* itemIds;
/* IDs of the CatalogTax objects to enable. At least one of `taxes_to_enable` or `taxes_to_disable` must be specified. [optional]
 */
@property(nonatomic) NSArray<NSString*>* taxesToEnable;
/* IDs of the CatalogTax objects to disable. At least one of `taxes_to_enable` or `taxes_to_disable` must be specified. [optional]
 */
@property(nonatomic) NSArray<NSString*>* taxesToDisable;

@end
