#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQBreakType.h"
@protocol SQBreakType;
@class SQBreakType;



@protocol SQUpdateBreakTypeRequest
@end

@interface SQUpdateBreakTypeRequest : SQObject

/* The updated `BreakType`. 
 */
@property(nonatomic) SQBreakType* breakType;

@end
