#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQInvoice.h"
@protocol SQInvoice;
@class SQInvoice;



@protocol SQUpdateInvoiceRequest
@end

@interface SQUpdateInvoiceRequest : SQObject

/* The invoice fields to update.  The current invoice version must be specified in the `version` field. For more information, see [Update an Invoice](https://developer.squareup.com/docs/invoices-api/update-invoices). 
 */
@property(nonatomic) SQInvoice* invoice;
/* A unique string that identifies the `UpdateInvoice` request. If you do not provide `idempotency_key` (or provide an empty string as the value), the endpoint treats each request as independent.  For more information, see [Idempotency](https://developer.squareup.com/docs/build-basics/common-api-patterns/idempotency). [optional]
 */
@property(nonatomic) NSString* idempotencyKey;
/* The list of fields to clear. For examples, see [Update an Invoice](https://developer.squareup.com/docs/invoices-api/update-invoices). 
 */
@property(nonatomic) NSArray<NSString*>* fieldsToClear;

@end
