#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQUpdateItemModifierListsRequest
@end

@interface SQUpdateItemModifierListsRequest : SQObject

/* The IDs of the catalog items associated with the CatalogModifierList objects being updated. 
 */
@property(nonatomic) NSArray<NSString*>* itemIds;
/* The IDs of the CatalogModifierList objects to enable for the CatalogItem. At least one of `modifier_lists_to_enable` or `modifier_lists_to_disable` must be specified. [optional]
 */
@property(nonatomic) NSArray<NSString*>* modifierListsToEnable;
/* The IDs of the CatalogModifierList objects to disable for the CatalogItem. At least one of `modifier_lists_to_enable` or `modifier_lists_to_disable` must be specified. [optional]
 */
@property(nonatomic) NSArray<NSString*>* modifierListsToDisable;

@end
