#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQV1ListPaymentsRequest
@end

@interface SQV1ListPaymentsRequest : SQObject

/* The order in which payments are listed in the response. [optional]
 */
@property(nonatomic) NSString* order;
/* The beginning of the requested reporting period, in ISO 8601 format. If this value is before January 1, 2013 (2013-01-01T00:00:00Z), this endpoint returns an error. Default value: The current time minus one year. [optional]
 */
@property(nonatomic) NSString* beginTime;
/* The end of the requested reporting period, in ISO 8601 format. If this value is more than one year greater than begin_time, this endpoint returns an error. Default value: The current time. [optional]
 */
@property(nonatomic) NSString* endTime;
/* The maximum number of payments to return in a single response. This value cannot exceed 200. [optional]
 */
@property(nonatomic) NSNumber* limit;
/* A pagination cursor to retrieve the next set of results for your original query to the endpoint. [optional]
 */
@property(nonatomic) NSString* batchToken;
/* Indicates whether or not to include partial payments in the response. Partial payments will have the tenders collected so far, but the itemizations will be empty until the payment is completed. [optional]
 */
@property(nonatomic) NSNumber* includePartial;

@end
