#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQV1Payment.h"
@protocol SQV1Payment;
@class SQV1Payment;



@protocol SQV1ListPaymentsResponse
@end

@interface SQV1ListPaymentsResponse : SQObject

/*  [optional]
 */
@property(nonatomic) NSArray<SQV1Payment>* items;

@end
