#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQV1Settlement.h"
@protocol SQV1Settlement;
@class SQV1Settlement;



@protocol SQV1ListSettlementsResponse
@end

@interface SQV1ListSettlementsResponse : SQObject

/*  [optional]
 */
@property(nonatomic) NSArray<SQV1Settlement>* items;

@end
