#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQV1Money.h"
@protocol SQV1Money;
@class SQV1Money;



@protocol SQV1SettlementEntry
@end

@interface SQV1SettlementEntry : SQObject

/* The settlement's unique identifier. [optional]
 */
@property(nonatomic) NSString* paymentId;
/* The settlement's current status. [optional]
 */
@property(nonatomic) NSString* type;
/* The total amount of money this entry contributes to the total settlement amount. [optional]
 */
@property(nonatomic) SQV1Money* amountMoney;
/* The amount of all Square fees associated with this settlement entry. This value is always negative or zero. [optional]
 */
@property(nonatomic) SQV1Money* feeMoney;

@end
