#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQV1Money.h"
#import "SQV1PaymentTax.h"
@protocol SQV1Money;
@class SQV1Money;
@protocol SQV1PaymentTax;
@class SQV1PaymentTax;



@protocol SQV1PaymentSurcharge
@end

@interface SQV1PaymentSurcharge : SQObject

/* The name of the surcharge. [optional]
 */
@property(nonatomic) NSString* name;
/* The amount of money applied to the order as a result of the surcharge. [optional]
 */
@property(nonatomic) SQV1Money* appliedMoney;
/* The amount of the surcharge as a percentage. The percentage is provided as a string representing the decimal equivalent of the percentage. For example, \"0.7\" corresponds to a 7% surcharge. Exactly one of rate or amount_money should be set. [optional]
 */
@property(nonatomic) NSString* rate;
/* The amount of the surcharge as a Money object. Exactly one of rate or amount_money should be set. [optional]
 */
@property(nonatomic) SQV1Money* amountMoney;
/* Indicates the source of the surcharge. For example, if it was applied as an automatic gratuity for a large group. [optional]
 */
@property(nonatomic) NSString* type;
/* Indicates whether the surcharge is taxable. [optional]
 */
@property(nonatomic) NSNumber* taxable;
/* The list of taxes that should be applied to the surcharge. [optional]
 */
@property(nonatomic) NSArray<SQV1PaymentTax>* taxes;
/* A Square-issued unique identifier associated with the surcharge. [optional]
 */
@property(nonatomic) NSString* surchargeId;

@end
