#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQError.h"
#import "SQV1Money.h"
@protocol SQError;
@class SQError;
@protocol SQV1Money;
@class SQV1Money;



@protocol SQV1PaymentTax
@end

@interface SQV1PaymentTax : SQObject

/* Any errors that occurred during the request. [optional]
 */
@property(nonatomic) NSArray<SQError>* errors;
/* The merchant-defined name of the tax. [optional]
 */
@property(nonatomic) NSString* name;
/* The amount of money that this tax adds to the payment. [optional]
 */
@property(nonatomic) SQV1Money* appliedMoney;
/* The rate of the tax, as a string representation of a decimal number. A value of 0.07 corresponds to a rate of 7%. [optional]
 */
@property(nonatomic) NSString* rate;
/* Whether the tax is an ADDITIVE tax or an INCLUSIVE tax. [optional]
 */
@property(nonatomic) NSString* inclusionType;
/* The ID of the tax, if available. Taxes applied in older versions of Square Register might not have an ID. [optional]
 */
@property(nonatomic) NSString* feeId;

@end
