#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQV1PhoneNumber
@end

@interface SQV1PhoneNumber : SQObject

/* The phone number's international calling code. For US phone numbers, this value is +1. 
 */
@property(nonatomic) NSString* callingCode;
/* The phone number. 
 */
@property(nonatomic) NSString* number;

@end
