#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQV1Device
@end

@interface SQV1Device : SQObject

/* The device's Square-issued ID. [optional]
 */
@property(nonatomic) NSString* _id;
/* The device's merchant-specified name. [optional]
 */
@property(nonatomic) NSString* name;

@end
