#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


#import "SQV1Money.h"
@protocol SQV1Money;
@class SQV1Money;



@protocol SQV1PaymentModifier
@end

@interface SQV1PaymentModifier : SQObject

/* The modifier option's name. [optional]
 */
@property(nonatomic) NSString* name;
/* The amount of money that this modifier option adds to the payment. [optional]
 */
@property(nonatomic) SQV1Money* appliedMoney;
/* The ID of the applied modifier option, if available. Modifier options applied in older versions of Square Register might not have an ID. [optional]
 */
@property(nonatomic) NSString* modifierOptionId;

@end
