#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQVendorContact
@end

@interface SQVendorContact : SQObject

/* A unique Square-generated ID for the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). This field is required when attempting to update a [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). [optional]
 */
@property(nonatomic) NSString* _id;
/* The name of the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). This field is required when attempting to create a [Vendor](https://developer.squareup.com/reference/square_2023-10-18/objects/Vendor). [optional]
 */
@property(nonatomic) NSString* name;
/* The email address of the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). [optional]
 */
@property(nonatomic) NSString* emailAddress;
/* The phone number of the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). [optional]
 */
@property(nonatomic) NSString* phoneNumber;
/* The state of the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). [optional]
 */
@property(nonatomic) NSNumber* removed;
/* The ordinal of the [VendorContact](https://developer.squareup.com/reference/square_2023-10-18/objects/VendorContact). 
 */
@property(nonatomic) NSNumber* ordinal;

@end
