#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQWebhookSubscription
@end

@interface SQWebhookSubscription : SQObject

/* A Square-generated unique ID for the subscription. [optional]
 */
@property(nonatomic) NSString* _id;
/* The name of this subscription. [optional]
 */
@property(nonatomic) NSString* name;
/* Indicates whether the subscription is enabled (`true`) or not (`false`). [optional]
 */
@property(nonatomic) NSNumber* enabled;
/* The event types associated with this subscription. [optional]
 */
@property(nonatomic) NSArray<NSString*>* eventTypes;
/* The URL to which webhooks are sent. [optional]
 */
@property(nonatomic) NSString* notificationUrl;
/* The API version of the subscription. This field is optional for `CreateWebhookSubscription`.  The value defaults to the API version used by the application. [optional]
 */
@property(nonatomic) NSString* apiVersion;
/* The Square-generated signature key used to validate the origin of the webhook event. [optional]
 */
@property(nonatomic) NSString* signatureKey;
/* The timestamp of when the subscription was created, in RFC 3339 format. For example, \"2016-09-04T23:59:33.123Z\". [optional]
 */
@property(nonatomic) NSString* createdAt;
/* The timestamp of when the subscription was last updated, in RFC 3339 format. For example, \"2016-09-04T23:59:33.123Z\". [optional]
 */
@property(nonatomic) NSString* updatedAt;

@end
