#import <Foundation/Foundation.h>
#import "SQObject.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SQWorkweekConfig
@end

@interface SQWorkweekConfig : SQObject

/* The UUID for this object. [optional]
 */
@property(nonatomic) NSString* _id;
/* The day of the week on which a business week starts for compensation purposes. 
 */
@property(nonatomic) NSString* startOfWeek;
/* The local time at which a business week starts. Represented as a string in `HH:MM` format (`HH:MM:SS` is also accepted, but seconds are truncated). 
 */
@property(nonatomic) NSString* startOfDayLocalTime;
/* Used for resolving concurrency issues. The request fails if the version provided does not match the server version at the time of the request. If not provided, Square executes a blind write; potentially overwriting data from another write. [optional]
 */
@property(nonatomic) NSNumber* version;
/* A read-only timestamp in RFC 3339 format; presented in UTC. [optional]
 */
@property(nonatomic) NSString* createdAt;
/* A read-only timestamp in RFC 3339 format; presented in UTC. [optional]
 */
@property(nonatomic) NSString* updatedAt;

@end
