#import <Foundation/Foundation.h>
#import "SQObtainTokenRequest.h"
#import "SQObtainTokenResponse.h"
#import "SQRenewTokenRequest.h"
#import "SQRenewTokenResponse.h"
#import "SQRetrieveTokenStatusResponse.h"
#import "SQRevokeTokenRequest.h"
#import "SQRevokeTokenResponse.h"
#import "SQApi.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SQOAuthApi: NSObject <SQApi>

extern NSString* kSQOAuthApiErrorDomain;
extern NSInteger kSQOAuthApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SQApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// ObtainToken
/// Returns an OAuth access token and a refresh token unless the  `short_lived` parameter is set to `true`, in which case the endpoint  returns only an access token.  The `grant_type` parameter specifies the type of OAuth request. If  `grant_type` is `authorization_code`, you must include the authorization  code you received when a seller granted you authorization. If `grant_type`  is `refresh_token`, you must provide a valid refresh token. If you're using  an old version of the Square APIs (prior to March 13, 2019), `grant_type`  can be `migration_token` and you must provide a valid migration token.  You can use the `scopes` parameter to limit the set of permissions granted  to the access token and refresh token. You can use the `short_lived` parameter  to create an access token that expires in 24 hours.  __Note:__ OAuth tokens should be encrypted and stored on a secure server.  Application clients should never interact directly with OAuth tokens.
///
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQObtainTokenResponse*
-(NSURLSessionTask*) obtainTokenWithBody: (SQObtainTokenRequest*) body
    completionHandler: (void (^)(SQObtainTokenResponse* output, NSError* error)) handler;


/// RenewToken
/// `RenewToken` is deprecated. For information about refreshing OAuth access tokens, see [Migrate from Renew to Refresh OAuth Tokens](https://developer.squareup.com/docs/oauth-api/migrate-to-refresh-tokens).  Renews an OAuth access token before it expires.  OAuth access tokens besides your application's personal access token expire after 30 days. You can also renew expired tokens within 15 days of their expiration. You cannot renew an access token that has been expired for more than 15 days. Instead, the associated user must recomplete the OAuth flow from the beginning.  __Important:__ The `Authorization` header for this endpoint must have the following format:  ``` Authorization: Client APPLICATION_SECRET ```  Replace `APPLICATION_SECRET` with the application secret on the **Credentials** page in the [Developer Dashboard](https://developer.squareup.com/apps).
///
/// @param clientId Your application ID, which is available on the **OAuth** page in the [Developer Dashboard](https://developer.squareup.com/apps).
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQRenewTokenResponse*
-(NSURLSessionTask*) renewTokenWithClientId: (NSString*) clientId
    body: (SQRenewTokenRequest*) body
    completionHandler: (void (^)(SQRenewTokenResponse* output, NSError* error)) handler;


/// RetrieveTokenStatus
/// Returns information about an [OAuth access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-an-oauth-access-token) or an application’s [personal access token](https://developer.squareup.com/docs/build-basics/access-tokens#get-a-personal-access-token).  Add the access token to the Authorization header of the request.  __Important:__ The `Authorization` header you provide to this endpoint must have the following format:  ``` Authorization: Bearer ACCESS_TOKEN ```  where `ACCESS_TOKEN` is a [valid production authorization credential](https://developer.squareup.com/docs/build-basics/access-tokens).  If the access token is expired or not a valid access token, the endpoint returns an `UNAUTHORIZED` error.
///
/// 
///  code:200 message:"Success"
///
/// @return SQRetrieveTokenStatusResponse*
-(NSURLSessionTask*) retrieveTokenStatusWithCompletionHandler: 
    (void (^)(SQRetrieveTokenStatusResponse* output, NSError* error)) handler;


/// RevokeToken
/// Revokes an access token generated with the OAuth flow.  If an account has more than one OAuth access token for your application, this endpoint revokes all of them, regardless of which token you specify.   __Important:__ The `Authorization` header for this endpoint must have the following format:  ``` Authorization: Client APPLICATION_SECRET ```  Replace `APPLICATION_SECRET` with the application secret on the **OAuth** page for your application in the Developer Dashboard.
///
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQRevokeTokenResponse*
-(NSURLSessionTask*) revokeTokenWithBody: (SQRevokeTokenRequest*) body
    completionHandler: (void (^)(SQRevokeTokenResponse* output, NSError* error)) handler;



@end
