#import <Foundation/Foundation.h>
#import "SQDeleteSnippetResponse.h"
#import "SQRetrieveSnippetResponse.h"
#import "SQUpsertSnippetRequest.h"
#import "SQUpsertSnippetResponse.h"
#import "SQApi.h"

/**
* Square Connect API
* Client library for accessing the Square Connect APIs
*
* OpenAPI spec version: 2.0
* Contact: developers@squareup.com
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SQSnippetsApi: NSObject <SQApi>

extern NSString* kSQSnippetsApiErrorDomain;
extern NSInteger kSQSnippetsApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SQApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// DeleteSnippet
/// Removes your snippet from a Square Online site.  You can call [ListSites](https://developer.squareup.com/reference/square_2023-10-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.   __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
///
/// @param siteId The ID of the site that contains the snippet.
/// 
///  code:200 message:"Success"
///
/// @return SQDeleteSnippetResponse*
-(NSURLSessionTask*) deleteSnippetWithSiteId: (NSString*) siteId
    completionHandler: (void (^)(SQDeleteSnippetResponse* output, NSError* error)) handler;


/// RetrieveSnippet
/// Retrieves your snippet from a Square Online site. A site can contain snippets from multiple snippet applications, but you can retrieve only the snippet that was added by your application.  You can call [ListSites](https://developer.squareup.com/reference/square_2023-10-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.   __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
///
/// @param siteId The ID of the site that contains the snippet.
/// 
///  code:200 message:"Success"
///
/// @return SQRetrieveSnippetResponse*
-(NSURLSessionTask*) retrieveSnippetWithSiteId: (NSString*) siteId
    completionHandler: (void (^)(SQRetrieveSnippetResponse* output, NSError* error)) handler;


/// UpsertSnippet
/// Adds a snippet to a Square Online site or updates the existing snippet on the site.  The snippet code is appended to the end of the `head` element on every page of the site, except checkout pages. A snippet application can add one snippet to a given site.   You can call [ListSites](https://developer.squareup.com/reference/square_2023-10-18/sites-api/list-sites) to get the IDs of the sites that belong to a seller.   __Note:__ Square Online APIs are publicly available as part of an early access program. For more information, see [Early access program for Square Online APIs](https://developer.squareup.com/docs/online-api#early-access-program-for-square-online-apis).
///
/// @param siteId The ID of the site where you want to add or update the snippet.
/// @param body An object containing the fields to POST for the request.  See the corresponding object definition for field details.
/// 
///  code:200 message:"Success"
///
/// @return SQUpsertSnippetResponse*
-(NSURLSessionTask*) upsertSnippetWithSiteId: (NSString*) siteId
    body: (SQUpsertSnippetRequest*) body
    completionHandler: (void (^)(SQUpsertSnippetResponse* output, NSError* error)) handler;



@end
